/* dh_validator.c generated by valac 0.56.16, the Vala compiler
 * generated from dh_validator.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <errno.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef gchar* (*DhLineinFunc) (gpointer user_data);

#define TYPE_DH_VALIDATOR (dh_validator_get_type ())
#define DH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_VALIDATOR, DhValidator))
#define IS_DH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_VALIDATOR))
#define DH_VALIDATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_DH_VALIDATOR, DhValidatorIface))

typedef struct _DhValidator DhValidator;
typedef struct _DhValidatorIface DhValidatorIface;

#define TYPE_DH_INT_VALIDATOR (dh_int_validator_get_type ())
#define DH_INT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_INT_VALIDATOR, DhIntValidator))
#define DH_INT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_INT_VALIDATOR, DhIntValidatorClass))
#define IS_DH_INT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_INT_VALIDATOR))
#define IS_DH_INT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_INT_VALIDATOR))
#define DH_INT_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_INT_VALIDATOR, DhIntValidatorClass))

typedef struct _DhIntValidator DhIntValidator;
typedef struct _DhIntValidatorClass DhIntValidatorClass;
typedef struct _DhIntValidatorPrivate DhIntValidatorPrivate;
enum  {
	DH_INT_VALIDATOR_0_PROPERTY,
	DH_INT_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_int_validator_properties[DH_INT_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_UINT_VALIDATOR (dh_uint_validator_get_type ())
#define DH_UINT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_UINT_VALIDATOR, DhUIntValidator))
#define DH_UINT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_UINT_VALIDATOR, DhUIntValidatorClass))
#define IS_DH_UINT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_UINT_VALIDATOR))
#define IS_DH_UINT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_UINT_VALIDATOR))
#define DH_UINT_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_UINT_VALIDATOR, DhUIntValidatorClass))

typedef struct _DhUIntValidator DhUIntValidator;
typedef struct _DhUIntValidatorClass DhUIntValidatorClass;
typedef struct _DhUIntValidatorPrivate DhUIntValidatorPrivate;
enum  {
	DH_UINT_VALIDATOR_0_PROPERTY,
	DH_UINT_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_uint_validator_properties[DH_UINT_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_DOUBLE_VALIDATOR (dh_double_validator_get_type ())
#define DH_DOUBLE_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidator))
#define DH_DOUBLE_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidatorClass))
#define IS_DH_DOUBLE_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_DOUBLE_VALIDATOR))
#define IS_DH_DOUBLE_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_DOUBLE_VALIDATOR))
#define DH_DOUBLE_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidatorClass))

typedef struct _DhDoubleValidator DhDoubleValidator;
typedef struct _DhDoubleValidatorClass DhDoubleValidatorClass;
typedef struct _DhDoubleValidatorPrivate DhDoubleValidatorPrivate;
enum  {
	DH_DOUBLE_VALIDATOR_0_PROPERTY,
	DH_DOUBLE_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_double_validator_properties[DH_DOUBLE_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_REGEX_VALIDATOR (dh_regex_validator_get_type ())
#define DH_REGEX_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_REGEX_VALIDATOR, DhRegexValidator))
#define DH_REGEX_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_REGEX_VALIDATOR, DhRegexValidatorClass))
#define IS_DH_REGEX_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_REGEX_VALIDATOR))
#define IS_DH_REGEX_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_REGEX_VALIDATOR))
#define DH_REGEX_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_REGEX_VALIDATOR, DhRegexValidatorClass))

typedef struct _DhRegexValidator DhRegexValidator;
typedef struct _DhRegexValidatorClass DhRegexValidatorClass;
typedef struct _DhRegexValidatorPrivate DhRegexValidatorPrivate;
enum  {
	DH_REGEX_VALIDATOR_0_PROPERTY,
	DH_REGEX_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_regex_validator_properties[DH_REGEX_VALIDATOR_NUM_PROPERTIES];
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

#define TYPE_DH_MATCH_VALIDATOR (dh_match_validator_get_type ())
#define DH_MATCH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_MATCH_VALIDATOR, DhMatchValidator))
#define DH_MATCH_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_MATCH_VALIDATOR, DhMatchValidatorClass))
#define IS_DH_MATCH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_MATCH_VALIDATOR))
#define IS_DH_MATCH_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_MATCH_VALIDATOR))
#define DH_MATCH_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_MATCH_VALIDATOR, DhMatchValidatorClass))

typedef struct _DhMatchValidator DhMatchValidator;
typedef struct _DhMatchValidatorClass DhMatchValidatorClass;
typedef struct _DhMatchValidatorPrivate DhMatchValidatorPrivate;
enum  {
	DH_MATCH_VALIDATOR_0_PROPERTY,
	DH_MATCH_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_match_validator_properties[DH_MATCH_VALIDATOR_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_DH_INT_ARRAY_VALIDATOR (dh_int_array_validator_get_type ())
#define DH_INT_ARRAY_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_INT_ARRAY_VALIDATOR, DhIntArrayValidator))
#define DH_INT_ARRAY_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_INT_ARRAY_VALIDATOR, DhIntArrayValidatorClass))
#define IS_DH_INT_ARRAY_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_INT_ARRAY_VALIDATOR))
#define IS_DH_INT_ARRAY_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_INT_ARRAY_VALIDATOR))
#define DH_INT_ARRAY_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_INT_ARRAY_VALIDATOR, DhIntArrayValidatorClass))

typedef struct _DhIntArrayValidator DhIntArrayValidator;
typedef struct _DhIntArrayValidatorClass DhIntArrayValidatorClass;
typedef struct _DhIntArrayValidatorPrivate DhIntArrayValidatorPrivate;
enum  {
	DH_INT_ARRAY_VALIDATOR_0_PROPERTY,
	DH_INT_ARRAY_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_int_array_validator_properties[DH_INT_ARRAY_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_ARG_INFO (dh_arg_info_get_type ())
#define DH_ARG_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_ARG_INFO, DhArgInfo))
#define DH_ARG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_ARG_INFO, DhArgInfoClass))
#define IS_DH_ARG_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_ARG_INFO))
#define IS_DH_ARG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_ARG_INFO))
#define DH_ARG_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_ARG_INFO, DhArgInfoClass))

typedef struct _DhArgInfo DhArgInfo;
typedef struct _DhArgInfoClass DhArgInfoClass;
typedef struct _DhArgInfoPrivate DhArgInfoPrivate;
enum  {
	DH_ARG_INFO_0_PROPERTY,
	DH_ARG_INFO_NUM_PROPERTIES
};
static GParamSpec* dh_arg_info_properties[DH_ARG_INFO_NUM_PROPERTIES];

#define TYPE_DH_OUT (dh_out_get_type ())
#define DH_OUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_OUT, DhOut))
#define DH_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_OUT, DhOutClass))
#define IS_DH_OUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_OUT))
#define IS_DH_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_OUT))
#define DH_OUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_OUT, DhOutClass))

typedef struct _DhOut DhOut;
typedef struct _DhOutClass DhOutClass;
typedef struct _DhOutPrivate DhOutPrivate;
enum  {
	DH_OUT_0_PROPERTY,
	DH_OUT_NUM_PROPERTIES
};
static GParamSpec* dh_out_properties[DH_OUT_NUM_PROPERTIES];
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _DhValidatorIface {
	GTypeInterface parent_iface;
	gboolean (*in_field) (DhValidator* self, gconstpointer val);
	void (*set_range) (DhValidator* self, gconstpointer min_val, gconstpointer max_val);
};

struct _DhIntValidator {
	GObject parent_instance;
	DhIntValidatorPrivate * priv;
};

struct _DhIntValidatorClass {
	GObjectClass parent_class;
};

struct _DhIntValidatorPrivate {
	gint64 min;
	gint64 max;
	gboolean ignore;
};

struct _DhUIntValidator {
	GObject parent_instance;
	DhUIntValidatorPrivate * priv;
};

struct _DhUIntValidatorClass {
	GObjectClass parent_class;
};

struct _DhUIntValidatorPrivate {
	guint64 min;
	guint64 max;
	gboolean ignore;
};

struct _DhDoubleValidator {
	GObject parent_instance;
	DhDoubleValidatorPrivate * priv;
};

struct _DhDoubleValidatorClass {
	GObjectClass parent_class;
};

struct _DhDoubleValidatorPrivate {
	gdouble min;
	gdouble max;
	gboolean ignore;
};

struct _DhRegexValidator {
	GObject parent_instance;
	DhRegexValidatorPrivate * priv;
};

struct _DhRegexValidatorClass {
	GObjectClass parent_class;
};

struct _DhRegexValidatorPrivate {
	GRegex* reg;
};

struct _DhMatchValidator {
	GObject parent_instance;
	DhMatchValidatorPrivate * priv;
};

struct _DhMatchValidatorClass {
	GObjectClass parent_class;
};

struct _DhMatchValidatorPrivate {
	gchar* match_str;
	gboolean ignore;
};

struct _DhIntArrayValidator {
	GObject parent_instance;
	DhIntArrayValidatorPrivate * priv;
	gchar* split_str;
};

struct _DhIntArrayValidatorClass {
	GObjectClass parent_class;
};

struct _DhIntArrayValidatorPrivate {
	GList* min;
	GList* max;
	gboolean allow_repeated;
	gboolean ignore;
};

struct _DhArgInfo {
	GObject parent_instance;
	DhArgInfoPrivate * priv;
};

struct _DhArgInfoClass {
	GObjectClass parent_class;
};

struct _DhArgInfoPrivate {
	GList* arg;
	GList* arg_fullname;
	GList* description;
};

struct _DhOut {
	GObject parent_instance;
	DhOutPrivate * priv;
};

struct _DhOutClass {
	GObjectClass parent_class;
};

static gint DhIntValidator_private_offset;
static gpointer dh_int_validator_parent_class = NULL;
static DhValidatorIface * dh_int_validator_dh_validator_parent_iface = NULL;
static gint DhUIntValidator_private_offset;
static gpointer dh_uint_validator_parent_class = NULL;
static DhValidatorIface * dh_uint_validator_dh_validator_parent_iface = NULL;
static gint DhDoubleValidator_private_offset;
static gpointer dh_double_validator_parent_class = NULL;
static DhValidatorIface * dh_double_validator_dh_validator_parent_iface = NULL;
static gint DhRegexValidator_private_offset;
static gpointer dh_regex_validator_parent_class = NULL;
static DhValidatorIface * dh_regex_validator_dh_validator_parent_iface = NULL;
static gint DhMatchValidator_private_offset;
static gpointer dh_match_validator_parent_class = NULL;
static DhValidatorIface * dh_match_validator_dh_validator_parent_iface = NULL;
static gint DhIntArrayValidator_private_offset;
static gpointer dh_int_array_validator_parent_class = NULL;
static DhValidatorIface * dh_int_array_validator_dh_validator_parent_iface = NULL;
static gint DhArgInfo_private_offset;
static gpointer dh_arg_info_parent_class = NULL;
static gpointer dh_out_parent_class = NULL;

VALA_EXTERN GType dh_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhValidator, g_object_unref)
VALA_EXTERN gboolean dh_validator_in_field (DhValidator* self,
                                gconstpointer val);
VALA_EXTERN void dh_validator_set_range (DhValidator* self,
                             gconstpointer min_val,
                             gconstpointer max_val);
static GType dh_validator_get_type_once (void);
VALA_EXTERN GType dh_int_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhIntValidator, g_object_unref)
VALA_EXTERN DhIntValidator* dh_int_validator_new_ignore_range (gboolean ir);
VALA_EXTERN DhIntValidator* dh_int_validator_construct_ignore_range (GType object_type,
                                                         gboolean ir);
VALA_EXTERN DhIntValidator* dh_int_validator_new (gint64 min,
                                      gint64 max);
VALA_EXTERN DhIntValidator* dh_int_validator_construct (GType object_type,
                                            gint64 min,
                                            gint64 max);
static gboolean dh_int_validator_real_in_field (DhValidator* base,
                                         gint64* val);
static void dh_int_validator_real_set_range (DhValidator* base,
                                      gint64* min_val,
                                      gint64* max_val);
static void dh_int_validator_finalize (GObject * obj);
static GType dh_int_validator_get_type_once (void);
VALA_EXTERN GType dh_uint_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhUIntValidator, g_object_unref)
VALA_EXTERN DhUIntValidator* dh_uint_validator_new_ignore_range (gboolean ir);
VALA_EXTERN DhUIntValidator* dh_uint_validator_construct_ignore_range (GType object_type,
                                                           gboolean ir);
VALA_EXTERN DhUIntValidator* dh_uint_validator_new (guint64 min,
                                        guint64 max);
VALA_EXTERN DhUIntValidator* dh_uint_validator_construct (GType object_type,
                                              guint64 min,
                                              guint64 max);
static gboolean dh_uint_validator_real_in_field (DhValidator* base,
                                          guint64* val);
static void dh_uint_validator_real_set_range (DhValidator* base,
                                       guint64* min_val,
                                       guint64* max_val);
static void dh_uint_validator_finalize (GObject * obj);
static GType dh_uint_validator_get_type_once (void);
VALA_EXTERN GType dh_double_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhDoubleValidator, g_object_unref)
VALA_EXTERN DhDoubleValidator* dh_double_validator_new_ignore_range (gboolean ir);
VALA_EXTERN DhDoubleValidator* dh_double_validator_construct_ignore_range (GType object_type,
                                                               gboolean ir);
VALA_EXTERN DhDoubleValidator* dh_double_validator_new (gdouble min,
                                            gdouble max);
VALA_EXTERN DhDoubleValidator* dh_double_validator_construct (GType object_type,
                                                  gdouble min,
                                                  gdouble max);
static gboolean dh_double_validator_real_in_field (DhValidator* base,
                                            gdouble* val);
static void dh_double_validator_real_set_range (DhValidator* base,
                                         gdouble* min_val,
                                         gdouble* max_val);
static void dh_double_validator_finalize (GObject * obj);
static GType dh_double_validator_get_type_once (void);
VALA_EXTERN GType dh_regex_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhRegexValidator, g_object_unref)
VALA_EXTERN DhRegexValidator* dh_regex_validator_new (GRegex* r);
VALA_EXTERN DhRegexValidator* dh_regex_validator_construct (GType object_type,
                                                GRegex* r);
static gboolean dh_regex_validator_real_in_field (DhValidator* base,
                                           const gchar* val);
static void dh_regex_validator_real_set_range (DhValidator* base,
                                        GRegex* min_val,
                                        GRegex* max_val);
static void dh_regex_validator_finalize (GObject * obj);
static GType dh_regex_validator_get_type_once (void);
VALA_EXTERN GType dh_match_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhMatchValidator, g_object_unref)
VALA_EXTERN DhMatchValidator* dh_match_validator_new_ignore_range (gboolean ir);
VALA_EXTERN DhMatchValidator* dh_match_validator_construct_ignore_range (GType object_type,
                                                             gboolean ir);
VALA_EXTERN DhMatchValidator* dh_match_validator_new (const gchar* str);
VALA_EXTERN DhMatchValidator* dh_match_validator_construct (GType object_type,
                                                const gchar* str);
static gboolean dh_match_validator_real_in_field (DhValidator* base,
                                           const gchar* val);
static void dh_match_validator_real_set_range (DhValidator* base,
                                        const gchar* min_val,
                                        const gchar* max_val);
static void dh_match_validator_finalize (GObject * obj);
static GType dh_match_validator_get_type_once (void);
VALA_EXTERN GType dh_int_array_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhIntArrayValidator, g_object_unref)
static void _g_free0_ (gpointer var);
static inline void _g_list_free__g_free0_ (GList* self);
VALA_EXTERN DhIntArrayValidator* dh_int_array_validator_new_ignore_range (gboolean ir);
VALA_EXTERN DhIntArrayValidator* dh_int_array_validator_construct_ignore_range (GType object_type,
                                                                    gboolean ir);
static gboolean dh_int_array_validator_real_in_field (DhValidator* base,
                                               GList* val);
static void dh_int_array_validator_real_set_range (DhValidator* base,
                                            GList* min_val,
                                            GList* max_val);
VALA_EXTERN void dh_int_array_validator_add_range (DhIntArrayValidator* self,
                                       gint64 min_val,
                                       gint64 max_val);
static gint64* _int64_dup (gint64* self);
VALA_EXTERN void dh_int_array_validator_set_split_str (DhIntArrayValidator* self,
                                           const gchar* sp_str);
VALA_EXTERN void dh_int_array_validator_set_allow_repeated (DhIntArrayValidator* self,
                                                gboolean ar);
VALA_EXTERN DhIntArrayValidator* dh_int_array_validator_new (void);
VALA_EXTERN DhIntArrayValidator* dh_int_array_validator_construct (GType object_type);
static void dh_int_array_validator_finalize (GObject * obj);
static GType dh_int_array_validator_get_type_once (void);
VALA_EXTERN GType dh_arg_info_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhArgInfo, g_object_unref)
VALA_EXTERN void dh_arg_info_add_arg (DhArgInfo* self,
                          gchar new_arg,
                          const gchar* new_arg_fullname,
                          const gchar* new_description);
VALA_EXTERN gchar* dh_arg_info_help_message (DhArgInfo* self,
                                 const gchar* gettext_package);
VALA_EXTERN gchar dh_arg_info_match_char (DhArgInfo* self,
                              const gchar* str);
VALA_EXTERN DhArgInfo* dh_arg_info_new (void);
VALA_EXTERN DhArgInfo* dh_arg_info_construct (GType object_type);
static void dh_arg_info_finalize (GObject * obj);
static GType dh_arg_info_get_type_once (void);
VALA_EXTERN GType dh_out_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhOut, g_object_unref)
VALA_EXTERN void dh_out_read_and_output (DhOut* self,
                             const gchar* tip_message,
                             const gchar* gettext_package,
                             DhArgInfo* arg,
                             DhValidator* validator,
                             gboolean get_array,
                             GValue* result);
VALA_EXTERN void dh_out_read_and_output_custom (DhOut* self,
                                    DhLineinFunc func,
                                    gpointer func_target,
                                    const gchar* tip_message,
                                    const gchar* gettext_package,
                                    DhArgInfo* arg,
                                    DhValidator* validator,
                                    gboolean get_array,
                                    GValue* result);
static gchar* _g_file_stream_read_line_dh_linein_func (gpointer self);
VALA_EXTERN void dh_out_read_and_output_as_int_custom (DhOut* self,
                                           DhLineinFunc func,
                                           gpointer func_target,
                                           const gchar* tip_message,
                                           const gchar* gettext_package,
                                           DhArgInfo* arg,
                                           gint64 min,
                                           gint64 max,
                                           gboolean get_array,
                                           GValue* result);
VALA_EXTERN void dh_out_read_and_output_as_int (DhOut* self,
                                    const gchar* tip_message,
                                    const gchar* gettext_package,
                                    DhArgInfo* arg,
                                    gint64 min,
                                    gint64 max,
                                    gboolean get_array,
                                    GValue* result);
VALA_EXTERN DhOut* dh_out_new (void);
VALA_EXTERN DhOut* dh_out_construct (GType object_type);
static GType dh_out_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

gboolean
dh_validator_in_field (DhValidator* self,
                       gconstpointer val)
{
	DhValidatorIface* _iface_;
	g_return_val_if_fail (self != NULL, FALSE);
	_iface_ = DH_VALIDATOR_GET_INTERFACE (self);
	if (_iface_->in_field) {
		return _iface_->in_field (self, val);
	}
	return FALSE;
}

void
dh_validator_set_range (DhValidator* self,
                        gconstpointer min_val,
                        gconstpointer max_val)
{
	DhValidatorIface* _iface_;
	g_return_if_fail (self != NULL);
	_iface_ = DH_VALIDATOR_GET_INTERFACE (self);
	if (_iface_->set_range) {
		_iface_->set_range (self, min_val, max_val);
	}
}

static void
dh_validator_default_init (DhValidatorIface * iface,
                           gpointer iface_data)
{
}

static GType
dh_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhValidatorIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_validator_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType dh_validator_type_id;
	dh_validator_type_id = g_type_register_static (G_TYPE_INTERFACE, "DhValidator", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (dh_validator_type_id, G_TYPE_OBJECT);
	return dh_validator_type_id;
}

GType
dh_validator_get_type (void)
{
	static volatile gsize dh_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_validator_type_id__once)) {
		GType dh_validator_type_id;
		dh_validator_type_id = dh_validator_get_type_once ();
		g_once_init_leave (&dh_validator_type_id__once, dh_validator_type_id);
	}
	return dh_validator_type_id__once;
}

static inline gpointer
dh_int_validator_get_instance_private (DhIntValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhIntValidator_private_offset);
}

DhIntValidator*
dh_int_validator_construct_ignore_range (GType object_type,
                                         gboolean ir)
{
	DhIntValidator * self = NULL;
	self = (DhIntValidator*) g_object_new (object_type, NULL);
	self->priv->ignore = ir;
	return self;
}

DhIntValidator*
dh_int_validator_new_ignore_range (gboolean ir)
{
	return dh_int_validator_construct_ignore_range (TYPE_DH_INT_VALIDATOR, ir);
}

DhIntValidator*
dh_int_validator_construct (GType object_type,
                            gint64 min,
                            gint64 max)
{
	DhIntValidator * self = NULL;
	self = (DhIntValidator*) g_object_new (object_type, NULL);
	dh_validator_set_range ((DhValidator*) self, &min, &max);
	return self;
}

DhIntValidator*
dh_int_validator_new (gint64 min,
                      gint64 max)
{
	return dh_int_validator_construct (TYPE_DH_INT_VALIDATOR, min, max);
}

static gboolean
dh_int_validator_real_in_field (DhValidator* base,
                                gint64* val)
{
	DhIntValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhIntValidator*) base;
	if (self->priv->ignore) {
		result = TRUE;
		return result;
	}
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_int_validator_real_set_range (DhValidator* base,
                                 gint64* min_val,
                                 gint64* max_val)
{
	DhIntValidator * self;
	self = (DhIntValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

static void
dh_int_validator_class_init (DhIntValidatorClass * klass,
                             gpointer klass_data)
{
	dh_int_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhIntValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_int_validator_finalize;
}

static void
dh_int_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                              gpointer iface_data)
{
	dh_int_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_int_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_int_validator_real_set_range;
}

static void
dh_int_validator_instance_init (DhIntValidator * self,
                                gpointer klass)
{
	self->priv = dh_int_validator_get_instance_private (self);
	self->priv->ignore = FALSE;
}

static void
dh_int_validator_finalize (GObject * obj)
{
	DhIntValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_INT_VALIDATOR, DhIntValidator);
	G_OBJECT_CLASS (dh_int_validator_parent_class)->finalize (obj);
}

static GType
dh_int_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhIntValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_int_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhIntValidator), 0, (GInstanceInitFunc) dh_int_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_int_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_int_validator_type_id;
	dh_int_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhIntValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_int_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhIntValidator_private_offset = g_type_add_instance_private (dh_int_validator_type_id, sizeof (DhIntValidatorPrivate));
	return dh_int_validator_type_id;
}

GType
dh_int_validator_get_type (void)
{
	static volatile gsize dh_int_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_int_validator_type_id__once)) {
		GType dh_int_validator_type_id;
		dh_int_validator_type_id = dh_int_validator_get_type_once ();
		g_once_init_leave (&dh_int_validator_type_id__once, dh_int_validator_type_id);
	}
	return dh_int_validator_type_id__once;
}

static inline gpointer
dh_uint_validator_get_instance_private (DhUIntValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhUIntValidator_private_offset);
}

DhUIntValidator*
dh_uint_validator_construct_ignore_range (GType object_type,
                                          gboolean ir)
{
	DhUIntValidator * self = NULL;
	self = (DhUIntValidator*) g_object_new (object_type, NULL);
	self->priv->ignore = ir;
	return self;
}

DhUIntValidator*
dh_uint_validator_new_ignore_range (gboolean ir)
{
	return dh_uint_validator_construct_ignore_range (TYPE_DH_UINT_VALIDATOR, ir);
}

DhUIntValidator*
dh_uint_validator_construct (GType object_type,
                             guint64 min,
                             guint64 max)
{
	DhUIntValidator * self = NULL;
	self = (DhUIntValidator*) g_object_new (object_type, NULL);
	dh_validator_set_range ((DhValidator*) self, &min, &max);
	return self;
}

DhUIntValidator*
dh_uint_validator_new (guint64 min,
                       guint64 max)
{
	return dh_uint_validator_construct (TYPE_DH_UINT_VALIDATOR, min, max);
}

static gboolean
dh_uint_validator_real_in_field (DhValidator* base,
                                 guint64* val)
{
	DhUIntValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhUIntValidator*) base;
	if (self->priv->ignore) {
		result = TRUE;
		return result;
	}
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_uint_validator_real_set_range (DhValidator* base,
                                  guint64* min_val,
                                  guint64* max_val)
{
	DhUIntValidator * self;
	self = (DhUIntValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

static void
dh_uint_validator_class_init (DhUIntValidatorClass * klass,
                              gpointer klass_data)
{
	dh_uint_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhUIntValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_uint_validator_finalize;
}

static void
dh_uint_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                               gpointer iface_data)
{
	dh_uint_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_uint_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_uint_validator_real_set_range;
}

static void
dh_uint_validator_instance_init (DhUIntValidator * self,
                                 gpointer klass)
{
	self->priv = dh_uint_validator_get_instance_private (self);
	self->priv->ignore = FALSE;
}

static void
dh_uint_validator_finalize (GObject * obj)
{
	DhUIntValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_UINT_VALIDATOR, DhUIntValidator);
	G_OBJECT_CLASS (dh_uint_validator_parent_class)->finalize (obj);
}

static GType
dh_uint_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhUIntValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_uint_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhUIntValidator), 0, (GInstanceInitFunc) dh_uint_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_uint_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_uint_validator_type_id;
	dh_uint_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhUIntValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_uint_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhUIntValidator_private_offset = g_type_add_instance_private (dh_uint_validator_type_id, sizeof (DhUIntValidatorPrivate));
	return dh_uint_validator_type_id;
}

GType
dh_uint_validator_get_type (void)
{
	static volatile gsize dh_uint_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_uint_validator_type_id__once)) {
		GType dh_uint_validator_type_id;
		dh_uint_validator_type_id = dh_uint_validator_get_type_once ();
		g_once_init_leave (&dh_uint_validator_type_id__once, dh_uint_validator_type_id);
	}
	return dh_uint_validator_type_id__once;
}

static inline gpointer
dh_double_validator_get_instance_private (DhDoubleValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhDoubleValidator_private_offset);
}

DhDoubleValidator*
dh_double_validator_construct_ignore_range (GType object_type,
                                            gboolean ir)
{
	DhDoubleValidator * self = NULL;
	self = (DhDoubleValidator*) g_object_new (object_type, NULL);
	self->priv->ignore = ir;
	return self;
}

DhDoubleValidator*
dh_double_validator_new_ignore_range (gboolean ir)
{
	return dh_double_validator_construct_ignore_range (TYPE_DH_DOUBLE_VALIDATOR, ir);
}

DhDoubleValidator*
dh_double_validator_construct (GType object_type,
                               gdouble min,
                               gdouble max)
{
	DhDoubleValidator * self = NULL;
	self = (DhDoubleValidator*) g_object_new (object_type, NULL);
	dh_validator_set_range ((DhValidator*) self, &min, &max);
	return self;
}

DhDoubleValidator*
dh_double_validator_new (gdouble min,
                         gdouble max)
{
	return dh_double_validator_construct (TYPE_DH_DOUBLE_VALIDATOR, min, max);
}

static gboolean
dh_double_validator_real_in_field (DhValidator* base,
                                   gdouble* val)
{
	DhDoubleValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhDoubleValidator*) base;
	if (self->priv->ignore) {
		result = TRUE;
		return result;
	}
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_double_validator_real_set_range (DhValidator* base,
                                    gdouble* min_val,
                                    gdouble* max_val)
{
	DhDoubleValidator * self;
	self = (DhDoubleValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

static void
dh_double_validator_class_init (DhDoubleValidatorClass * klass,
                                gpointer klass_data)
{
	dh_double_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhDoubleValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_double_validator_finalize;
}

static void
dh_double_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                 gpointer iface_data)
{
	dh_double_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_double_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_double_validator_real_set_range;
}

static void
dh_double_validator_instance_init (DhDoubleValidator * self,
                                   gpointer klass)
{
	self->priv = dh_double_validator_get_instance_private (self);
	self->priv->ignore = FALSE;
}

static void
dh_double_validator_finalize (GObject * obj)
{
	DhDoubleValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidator);
	G_OBJECT_CLASS (dh_double_validator_parent_class)->finalize (obj);
}

static GType
dh_double_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhDoubleValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_double_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhDoubleValidator), 0, (GInstanceInitFunc) dh_double_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_double_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_double_validator_type_id;
	dh_double_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhDoubleValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_double_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhDoubleValidator_private_offset = g_type_add_instance_private (dh_double_validator_type_id, sizeof (DhDoubleValidatorPrivate));
	return dh_double_validator_type_id;
}

GType
dh_double_validator_get_type (void)
{
	static volatile gsize dh_double_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_double_validator_type_id__once)) {
		GType dh_double_validator_type_id;
		dh_double_validator_type_id = dh_double_validator_get_type_once ();
		g_once_init_leave (&dh_double_validator_type_id__once, dh_double_validator_type_id);
	}
	return dh_double_validator_type_id__once;
}

static inline gpointer
dh_regex_validator_get_instance_private (DhRegexValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhRegexValidator_private_offset);
}

DhRegexValidator*
dh_regex_validator_construct (GType object_type,
                              GRegex* r)
{
	DhRegexValidator * self = NULL;
	g_return_val_if_fail (r != NULL, NULL);
	self = (DhRegexValidator*) g_object_new (object_type, NULL);
	dh_validator_set_range ((DhValidator*) self, r, NULL);
	return self;
}

DhRegexValidator*
dh_regex_validator_new (GRegex* r)
{
	return dh_regex_validator_construct (TYPE_DH_REGEX_VALIDATOR, r);
}

static gboolean
dh_regex_validator_real_in_field (DhValidator* base,
                                  const gchar* val)
{
	DhRegexValidator * self;
	GRegex* _tmp0_;
	gboolean result;
	self = (DhRegexValidator*) base;
	g_return_val_if_fail (val != NULL, FALSE);
	_tmp0_ = self->priv->reg;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		GRegex* _tmp1_;
		_tmp1_ = self->priv->reg;
		result = g_regex_match (_tmp1_, val, 0, NULL);
		return result;
	}
}

static gpointer
_g_regex_ref0 (gpointer self)
{
	return self ? g_regex_ref (self) : NULL;
}

static void
dh_regex_validator_real_set_range (DhValidator* base,
                                   GRegex* min_val,
                                   GRegex* max_val)
{
	DhRegexValidator * self;
	self = (DhRegexValidator*) base;
	if (min_val != NULL) {
		GRegex* _tmp0_;
		_tmp0_ = _g_regex_ref0 (min_val);
		_g_regex_unref0 (self->priv->reg);
		self->priv->reg = _tmp0_;
	} else {
		GRegex* _tmp1_;
		_tmp1_ = _g_regex_ref0 (max_val);
		_g_regex_unref0 (self->priv->reg);
		self->priv->reg = _tmp1_;
	}
}

static void
dh_regex_validator_class_init (DhRegexValidatorClass * klass,
                               gpointer klass_data)
{
	dh_regex_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhRegexValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_regex_validator_finalize;
}

static void
dh_regex_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                gpointer iface_data)
{
	dh_regex_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_regex_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_regex_validator_real_set_range;
}

static void
dh_regex_validator_instance_init (DhRegexValidator * self,
                                  gpointer klass)
{
	self->priv = dh_regex_validator_get_instance_private (self);
}

static void
dh_regex_validator_finalize (GObject * obj)
{
	DhRegexValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_REGEX_VALIDATOR, DhRegexValidator);
	_g_regex_unref0 (self->priv->reg);
	G_OBJECT_CLASS (dh_regex_validator_parent_class)->finalize (obj);
}

static GType
dh_regex_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhRegexValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_regex_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhRegexValidator), 0, (GInstanceInitFunc) dh_regex_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_regex_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_regex_validator_type_id;
	dh_regex_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhRegexValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_regex_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhRegexValidator_private_offset = g_type_add_instance_private (dh_regex_validator_type_id, sizeof (DhRegexValidatorPrivate));
	return dh_regex_validator_type_id;
}

GType
dh_regex_validator_get_type (void)
{
	static volatile gsize dh_regex_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_regex_validator_type_id__once)) {
		GType dh_regex_validator_type_id;
		dh_regex_validator_type_id = dh_regex_validator_get_type_once ();
		g_once_init_leave (&dh_regex_validator_type_id__once, dh_regex_validator_type_id);
	}
	return dh_regex_validator_type_id__once;
}

static inline gpointer
dh_match_validator_get_instance_private (DhMatchValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhMatchValidator_private_offset);
}

DhMatchValidator*
dh_match_validator_construct_ignore_range (GType object_type,
                                           gboolean ir)
{
	DhMatchValidator * self = NULL;
	self = (DhMatchValidator*) g_object_new (object_type, NULL);
	self->priv->ignore = ir;
	return self;
}

DhMatchValidator*
dh_match_validator_new_ignore_range (gboolean ir)
{
	return dh_match_validator_construct_ignore_range (TYPE_DH_MATCH_VALIDATOR, ir);
}

DhMatchValidator*
dh_match_validator_construct (GType object_type,
                              const gchar* str)
{
	DhMatchValidator * self = NULL;
	g_return_val_if_fail (str != NULL, NULL);
	self = (DhMatchValidator*) g_object_new (object_type, NULL);
	dh_validator_set_range ((DhValidator*) self, str, "");
	return self;
}

DhMatchValidator*
dh_match_validator_new (const gchar* str)
{
	return dh_match_validator_construct (TYPE_DH_MATCH_VALIDATOR, str);
}

static gboolean
dh_match_validator_real_in_field (DhValidator* base,
                                  const gchar* val)
{
	DhMatchValidator * self;
	const gchar* _tmp0_;
	gboolean result;
	self = (DhMatchValidator*) base;
	g_return_val_if_fail (val != NULL, FALSE);
	if (self->priv->ignore) {
		result = TRUE;
		return result;
	}
	_tmp0_ = self->priv->match_str;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		const gchar* _tmp1_;
		_tmp1_ = self->priv->match_str;
		result = g_regex_match_simple (_tmp1_, val, 0, 0);
		return result;
	}
}

static void
dh_match_validator_real_set_range (DhValidator* base,
                                   const gchar* min_val,
                                   const gchar* max_val)
{
	DhMatchValidator * self;
	self = (DhMatchValidator*) base;
	g_return_if_fail (min_val != NULL);
	g_return_if_fail (max_val != NULL);
	if (min_val != NULL) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (min_val);
		_g_free0 (self->priv->match_str);
		self->priv->match_str = _tmp0_;
	} else {
		gchar* _tmp1_;
		_tmp1_ = g_strdup (max_val);
		_g_free0 (self->priv->match_str);
		self->priv->match_str = _tmp1_;
	}
}

static void
dh_match_validator_class_init (DhMatchValidatorClass * klass,
                               gpointer klass_data)
{
	dh_match_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhMatchValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_match_validator_finalize;
}

static void
dh_match_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                gpointer iface_data)
{
	dh_match_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_match_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_match_validator_real_set_range;
}

static void
dh_match_validator_instance_init (DhMatchValidator * self,
                                  gpointer klass)
{
	self->priv = dh_match_validator_get_instance_private (self);
	self->priv->ignore = FALSE;
}

static void
dh_match_validator_finalize (GObject * obj)
{
	DhMatchValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_MATCH_VALIDATOR, DhMatchValidator);
	_g_free0 (self->priv->match_str);
	G_OBJECT_CLASS (dh_match_validator_parent_class)->finalize (obj);
}

static GType
dh_match_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhMatchValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_match_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhMatchValidator), 0, (GInstanceInitFunc) dh_match_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_match_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_match_validator_type_id;
	dh_match_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhMatchValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_match_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhMatchValidator_private_offset = g_type_add_instance_private (dh_match_validator_type_id, sizeof (DhMatchValidatorPrivate));
	return dh_match_validator_type_id;
}

GType
dh_match_validator_get_type (void)
{
	static volatile gsize dh_match_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_match_validator_type_id__once)) {
		GType dh_match_validator_type_id;
		dh_match_validator_type_id = dh_match_validator_get_type_once ();
		g_once_init_leave (&dh_match_validator_type_id__once, dh_match_validator_type_id);
	}
	return dh_match_validator_type_id__once;
}

static inline gpointer
dh_int_array_validator_get_instance_private (DhIntArrayValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhIntArrayValidator_private_offset);
}

static void
_g_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_free (var), NULL));
}

static inline void
_g_list_free__g_free0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_free0_);
}

DhIntArrayValidator*
dh_int_array_validator_construct_ignore_range (GType object_type,
                                               gboolean ir)
{
	DhIntArrayValidator * self = NULL;
	self = (DhIntArrayValidator*) g_object_new (object_type, NULL);
	self->priv->ignore = ir;
	return self;
}

DhIntArrayValidator*
dh_int_array_validator_new_ignore_range (gboolean ir)
{
	return dh_int_array_validator_construct_ignore_range (TYPE_DH_INT_ARRAY_VALIDATOR, ir);
}

static gboolean
dh_int_array_validator_real_in_field (DhValidator* base,
                                      GList* val)
{
	DhIntArrayValidator * self;
	guint len = 0U;
	GList* _tmp0_;
	gboolean same_range = FALSE;
	gboolean result;
	self = (DhIntArrayValidator*) base;
	if (self->priv->ignore) {
		result = TRUE;
		return result;
	}
	_tmp0_ = self->priv->min;
	len = g_list_length (_tmp0_);
	same_range = FALSE;
	if (len == ((guint) 1)) {
		same_range = TRUE;
	}
	if (!self->priv->allow_repeated) {
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp1_ = FALSE;
				_tmp1_ = TRUE;
				while (TRUE) {
					gint64 temp = 0LL;
					gconstpointer _tmp3_;
					if (!_tmp1_) {
						gint _tmp2_;
						_tmp2_ = i;
						i = _tmp2_ + 1;
					}
					_tmp1_ = FALSE;
					if (!(((guint) i) < g_list_length (val))) {
						break;
					}
					_tmp3_ = g_list_nth_data (val, (guint) i);
					temp = *((gint64*) _tmp3_);
					{
						gint j = 0;
						j = i + 1;
						{
							gboolean _tmp4_ = FALSE;
							_tmp4_ = TRUE;
							while (TRUE) {
								gint64 temp_1 = 0LL;
								gconstpointer _tmp6_;
								if (!_tmp4_) {
									gint _tmp5_;
									_tmp5_ = j;
									j = _tmp5_ + 1;
								}
								_tmp4_ = FALSE;
								if (!(((guint) j) < g_list_length (val))) {
									break;
								}
								_tmp6_ = g_list_nth_data (val, (guint) j);
								temp_1 = *((gint64*) _tmp6_);
								if (temp == temp_1) {
									result = FALSE;
									return result;
								}
							}
						}
					}
				}
			}
		}
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				gint64 min_val = 0LL;
				gint64 max_val = 0LL;
				gboolean _tmp17_ = FALSE;
				gconstpointer _tmp18_;
				if (!_tmp7_) {
					gint _tmp8_;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp7_ = FALSE;
				if (!(((guint) i) < g_list_length (val))) {
					break;
				}
				if (same_range) {
					GList* _tmp9_;
					gconstpointer _tmp10_;
					GList* _tmp11_;
					gconstpointer _tmp12_;
					_tmp9_ = self->priv->min;
					_tmp10_ = g_list_nth_data (_tmp9_, (guint) 0);
					min_val = (gint64) (*((gint64*) _tmp10_));
					_tmp11_ = self->priv->max;
					_tmp12_ = g_list_nth_data (_tmp11_, (guint) 0);
					max_val = (gint64) (*((gint64*) _tmp12_));
				} else {
					GList* _tmp13_;
					gconstpointer _tmp14_;
					GList* _tmp15_;
					gconstpointer _tmp16_;
					_tmp13_ = self->priv->min;
					_tmp14_ = g_list_nth_data (_tmp13_, (guint) i);
					min_val = (gint64) (*((gint64*) _tmp14_));
					_tmp15_ = self->priv->max;
					_tmp16_ = g_list_nth_data (_tmp15_, (guint) i);
					max_val = (gint64) (*((gint64*) _tmp16_));
				}
				_tmp18_ = g_list_nth_data (val, (guint) i);
				if ((*((gint64*) _tmp18_)) < min_val) {
					_tmp17_ = TRUE;
				} else {
					gconstpointer _tmp19_;
					_tmp19_ = g_list_nth_data (val, (guint) i);
					_tmp17_ = (*((gint64*) _tmp19_)) > max_val;
				}
				if (_tmp17_) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}

static void
dh_int_array_validator_real_set_range (DhValidator* base,
                                       GList* min_val,
                                       GList* max_val)
{
	DhIntArrayValidator * self;
	GList* _tmp0_;
	GList* _tmp1_;
	self = (DhIntArrayValidator*) base;
	_tmp0_ = g_list_copy (min_val);
	(self->priv->min == NULL) ? NULL : (self->priv->min = (_g_list_free__g_free0_ (self->priv->min), NULL));
	self->priv->min = (GList*) _tmp0_;
	_tmp1_ = g_list_copy (max_val);
	(self->priv->max == NULL) ? NULL : (self->priv->max = (_g_list_free__g_free0_ (self->priv->max), NULL));
	self->priv->max = (GList*) _tmp1_;
}

static gint64*
_int64_dup (gint64* self)
{
	gint64* dup;
	dup = g_new0 (gint64, 1);
	memcpy (dup, self, sizeof (gint64));
	return dup;
}

static gpointer
__int64_dup0 (gpointer self)
{
	return self ? _int64_dup (self) : NULL;
}

void
dh_int_array_validator_add_range (DhIntArrayValidator* self,
                                  gint64 min_val,
                                  gint64 max_val)
{
	gint64* _tmp0_;
	gint64* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = __int64_dup0 (&min_val);
	self->priv->min = g_list_append (self->priv->min, _tmp0_);
	_tmp1_ = __int64_dup0 (&max_val);
	self->priv->max = g_list_append (self->priv->max, _tmp1_);
}

void
dh_int_array_validator_set_split_str (DhIntArrayValidator* self,
                                      const gchar* sp_str)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sp_str != NULL);
	_tmp0_ = g_strdup (sp_str);
	_g_free0 (self->split_str);
	self->split_str = _tmp0_;
}

void
dh_int_array_validator_set_allow_repeated (DhIntArrayValidator* self,
                                           gboolean ar)
{
	g_return_if_fail (self != NULL);
	self->priv->allow_repeated = ar;
}

DhIntArrayValidator*
dh_int_array_validator_construct (GType object_type)
{
	DhIntArrayValidator * self = NULL;
	self = (DhIntArrayValidator*) g_object_new (object_type, NULL);
	return self;
}

DhIntArrayValidator*
dh_int_array_validator_new (void)
{
	return dh_int_array_validator_construct (TYPE_DH_INT_ARRAY_VALIDATOR);
}

static void
dh_int_array_validator_class_init (DhIntArrayValidatorClass * klass,
                                   gpointer klass_data)
{
	dh_int_array_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhIntArrayValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_int_array_validator_finalize;
}

static void
dh_int_array_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                    gpointer iface_data)
{
	dh_int_array_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_int_array_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_int_array_validator_real_set_range;
}

static void
dh_int_array_validator_instance_init (DhIntArrayValidator * self,
                                      gpointer klass)
{
	self->priv = dh_int_array_validator_get_instance_private (self);
	self->priv->min = NULL;
	self->priv->max = NULL;
	self->priv->ignore = FALSE;
}

static void
dh_int_array_validator_finalize (GObject * obj)
{
	DhIntArrayValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_INT_ARRAY_VALIDATOR, DhIntArrayValidator);
	(self->priv->min == NULL) ? NULL : (self->priv->min = (_g_list_free__g_free0_ (self->priv->min), NULL));
	(self->priv->max == NULL) ? NULL : (self->priv->max = (_g_list_free__g_free0_ (self->priv->max), NULL));
	_g_free0 (self->split_str);
	G_OBJECT_CLASS (dh_int_array_validator_parent_class)->finalize (obj);
}

static GType
dh_int_array_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhIntArrayValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_int_array_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhIntArrayValidator), 0, (GInstanceInitFunc) dh_int_array_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_int_array_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_int_array_validator_type_id;
	dh_int_array_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhIntArrayValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_int_array_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhIntArrayValidator_private_offset = g_type_add_instance_private (dh_int_array_validator_type_id, sizeof (DhIntArrayValidatorPrivate));
	return dh_int_array_validator_type_id;
}

GType
dh_int_array_validator_get_type (void)
{
	static volatile gsize dh_int_array_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_int_array_validator_type_id__once)) {
		GType dh_int_array_validator_type_id;
		dh_int_array_validator_type_id = dh_int_array_validator_get_type_once ();
		g_once_init_leave (&dh_int_array_validator_type_id__once, dh_int_array_validator_type_id);
	}
	return dh_int_array_validator_type_id__once;
}

static inline gpointer
dh_arg_info_get_instance_private (DhArgInfo* self)
{
	return G_STRUCT_MEMBER_P (self, DhArgInfo_private_offset);
}

void
dh_arg_info_add_arg (DhArgInfo* self,
                     gchar new_arg,
                     const gchar* new_arg_fullname,
                     const gchar* new_description)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (new_arg_fullname != NULL);
	g_return_if_fail (new_description != NULL);
	self->priv->arg = g_list_append (self->priv->arg, (gpointer) ((gintptr) new_arg));
	_tmp0_ = g_strdup (new_arg_fullname);
	self->priv->arg_fullname = g_list_append (self->priv->arg_fullname, _tmp0_);
	_tmp1_ = g_strdup (new_description);
	self->priv->description = g_list_append (self->priv->description, _tmp1_);
}

gchar*
dh_arg_info_help_message (DhArgInfo* self,
                          const gchar* gettext_package)
{
	gchar* str = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (gettext_package != NULL, NULL);
	_tmp0_ = g_strdup (g_dgettext ("dhutil", "The arguments are:\n"));
	str = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				GList* _tmp3_;
				const gchar* _tmp4_;
				gchar* _tmp5_;
				gchar* temp_str = NULL;
				GList* _tmp6_;
				gconstpointer _tmp7_;
				gchar* _tmp8_;
				const gchar* _tmp9_;
				const gchar* _tmp10_;
				gchar* _tmp11_;
				const gchar* _tmp12_;
				gchar* _tmp13_;
				const gchar* _tmp14_;
				GList* _tmp15_;
				gconstpointer _tmp16_;
				gchar* _tmp17_;
				const gchar* _tmp18_;
				gchar* _tmp19_;
				const gchar* _tmp20_;
				GList* _tmp21_;
				gconstpointer _tmp22_;
				gchar* _tmp23_;
				const gchar* _tmp24_;
				gchar* _tmp25_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = self->priv->arg;
				if (!(((guint) i) < g_list_length (_tmp3_))) {
					break;
				}
				_tmp4_ = str;
				_tmp5_ = g_strconcat (_tmp4_, "\"", NULL);
				_g_free0 (str);
				str = _tmp5_;
				_tmp6_ = self->priv->arg;
				_tmp7_ = g_list_nth_data (_tmp6_, (guint) i);
				_tmp8_ = g_strnfill ((gsize) 1, (gchar) ((gintptr) _tmp7_));
				temp_str = _tmp8_;
				_tmp9_ = str;
				_tmp10_ = temp_str;
				_tmp11_ = g_strconcat (_tmp9_, _tmp10_, NULL);
				_g_free0 (str);
				str = _tmp11_;
				_tmp12_ = str;
				_tmp13_ = g_strconcat (_tmp12_, "\", \"", NULL);
				_g_free0 (str);
				str = _tmp13_;
				_tmp14_ = str;
				_tmp15_ = self->priv->arg_fullname;
				_tmp16_ = g_list_nth_data (_tmp15_, (guint) i);
				_tmp17_ = g_strconcat (_tmp14_, (const gchar*) _tmp16_, NULL);
				_g_free0 (str);
				str = _tmp17_;
				_tmp18_ = str;
				_tmp19_ = g_strconcat (_tmp18_, "\", \"", NULL);
				_g_free0 (str);
				str = _tmp19_;
				_tmp20_ = str;
				_tmp21_ = self->priv->description;
				_tmp22_ = g_list_nth_data (_tmp21_, (guint) i);
				_tmp23_ = g_strconcat (_tmp20_, g_dgettext (gettext_package, (const gchar*) _tmp22_), NULL);
				_g_free0 (str);
				str = _tmp23_;
				_tmp24_ = str;
				_tmp25_ = g_strconcat (_tmp24_, "\"\n", NULL);
				_g_free0 (str);
				str = _tmp25_;
				_g_free0 (temp_str);
			}
		}
	}
	result = str;
	return result;
}

gchar
dh_arg_info_match_char (DhArgInfo* self,
                        const gchar* str)
{
	gchar* pstr = NULL;
	gchar* _tmp0_;
	const gchar* _tmp22_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	g_return_val_if_fail (str != NULL, '\0');
	_tmp0_ = g_ascii_strdown (str, (gssize) -1);
	pstr = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				GList* _tmp3_;
				gchar* match_str = NULL;
				gchar* _tmp4_;
				const gchar* _tmp5_;
				GList* _tmp6_;
				gconstpointer _tmp7_;
				gchar* _tmp8_;
				const gchar* _tmp9_;
				const gchar* _tmp10_;
				gchar* _tmp13_;
				const gchar* _tmp14_;
				GList* _tmp15_;
				gconstpointer _tmp16_;
				gchar* _tmp17_;
				const gchar* _tmp18_;
				const gchar* _tmp19_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = self->priv->arg;
				if (!(((guint) i) < g_list_length (_tmp3_))) {
					break;
				}
				_tmp4_ = g_strdup ("^%c$");
				match_str = _tmp4_;
				_tmp5_ = match_str;
				_tmp6_ = self->priv->arg;
				_tmp7_ = g_list_nth_data (_tmp6_, (guint) i);
				_tmp8_ = g_strdup_printf (_tmp5_, (gchar) ((gintptr) _tmp7_));
				_g_free0 (match_str);
				match_str = _tmp8_;
				_tmp9_ = match_str;
				_tmp10_ = pstr;
				if (g_regex_match_simple (_tmp9_, _tmp10_, 0, 0)) {
					GList* _tmp11_;
					gconstpointer _tmp12_;
					_tmp11_ = self->priv->arg;
					_tmp12_ = g_list_nth_data (_tmp11_, (guint) i);
					result = (gchar) ((gintptr) _tmp12_);
					_g_free0 (match_str);
					_g_free0 (pstr);
					return result;
				}
				_tmp13_ = g_strdup ("^%s$");
				_g_free0 (match_str);
				match_str = _tmp13_;
				_tmp14_ = match_str;
				_tmp15_ = self->priv->arg_fullname;
				_tmp16_ = g_list_nth_data (_tmp15_, (guint) i);
				_tmp17_ = g_strdup_printf (_tmp14_, (const gchar*) _tmp16_);
				_g_free0 (match_str);
				match_str = _tmp17_;
				_tmp18_ = match_str;
				_tmp19_ = pstr;
				if (g_regex_match_simple (_tmp18_, _tmp19_, 0, 0)) {
					GList* _tmp20_;
					gconstpointer _tmp21_;
					_tmp20_ = self->priv->arg;
					_tmp21_ = g_list_nth_data (_tmp20_, (guint) i);
					result = (gchar) ((gintptr) _tmp21_);
					_g_free0 (match_str);
					_g_free0 (pstr);
					return result;
				}
				_g_free0 (match_str);
			}
		}
	}
	_tmp22_ = pstr;
	if (g_strcmp0 (_tmp22_, "") == 0) {
		GList* _tmp23_;
		gconstpointer _tmp24_;
		_tmp23_ = self->priv->arg;
		_tmp24_ = g_list_nth_data (_tmp23_, (guint) 0);
		result = (gchar) ((gintptr) _tmp24_);
		_g_free0 (pstr);
		return result;
	}
	result = (gchar) 0;
	_g_free0 (pstr);
	return result;
}

DhArgInfo*
dh_arg_info_construct (GType object_type)
{
	DhArgInfo * self = NULL;
	self = (DhArgInfo*) g_object_new (object_type, NULL);
	return self;
}

DhArgInfo*
dh_arg_info_new (void)
{
	return dh_arg_info_construct (TYPE_DH_ARG_INFO);
}

static void
dh_arg_info_class_init (DhArgInfoClass * klass,
                        gpointer klass_data)
{
	dh_arg_info_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhArgInfo_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_arg_info_finalize;
}

static void
dh_arg_info_instance_init (DhArgInfo * self,
                           gpointer klass)
{
	self->priv = dh_arg_info_get_instance_private (self);
}

static void
dh_arg_info_finalize (GObject * obj)
{
	DhArgInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_ARG_INFO, DhArgInfo);
	(self->priv->arg == NULL) ? NULL : (self->priv->arg = (g_list_free (self->priv->arg), NULL));
	(self->priv->arg_fullname == NULL) ? NULL : (self->priv->arg_fullname = (_g_list_free__g_free0_ (self->priv->arg_fullname), NULL));
	(self->priv->description == NULL) ? NULL : (self->priv->description = (_g_list_free__g_free0_ (self->priv->description), NULL));
	G_OBJECT_CLASS (dh_arg_info_parent_class)->finalize (obj);
}

static GType
dh_arg_info_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhArgInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_arg_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhArgInfo), 0, (GInstanceInitFunc) dh_arg_info_instance_init, NULL };
	GType dh_arg_info_type_id;
	dh_arg_info_type_id = g_type_register_static (G_TYPE_OBJECT, "DhArgInfo", &g_define_type_info, 0);
	DhArgInfo_private_offset = g_type_add_instance_private (dh_arg_info_type_id, sizeof (DhArgInfoPrivate));
	return dh_arg_info_type_id;
}

GType
dh_arg_info_get_type (void)
{
	static volatile gsize dh_arg_info_type_id__once = 0;
	if (g_once_init_enter (&dh_arg_info_type_id__once)) {
		GType dh_arg_info_type_id;
		dh_arg_info_type_id = dh_arg_info_get_type_once ();
		g_once_init_leave (&dh_arg_info_type_id__once, dh_arg_info_type_id);
	}
	return dh_arg_info_type_id__once;
}

static gchar*
g_file_stream_read_line (FILE* self)
{
	gint c = 0;
	GString* ret = NULL;
	GString* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	ret = NULL;
	while (TRUE) {
		GString* _tmp0_;
		GString* _tmp2_;
		c = fgetc (self);
		if (!(c != EOF)) {
			break;
		}
		_tmp0_ = ret;
		if (_tmp0_ == NULL) {
			GString* _tmp1_;
			_tmp1_ = g_string_new ("");
			_g_string_free0 (ret);
			ret = _tmp1_;
		}
		if (c == ((gint) '\n')) {
			break;
		}
		_tmp2_ = ret;
		g_string_append_c ((GString*) _tmp2_, (gchar) c);
	}
	_tmp3_ = ret;
	if (_tmp3_ == NULL) {
		result = NULL;
		_g_string_free0 (ret);
		return result;
	} else {
		GString* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = ret;
		_tmp5_ = ((GString*) _tmp4_)->str;
		_tmp6_ = g_strdup (_tmp5_);
		result = _tmp6_;
		_g_string_free0 (ret);
		return result;
	}
}

static gchar*
_g_file_stream_read_line_dh_linein_func (gpointer self)
{
	gchar* result;
	result = g_file_stream_read_line ((FILE*) self);
	return result;
}

void
dh_out_read_and_output (DhOut* self,
                        const gchar* tip_message,
                        const gchar* gettext_package,
                        DhArgInfo* arg,
                        DhValidator* validator,
                        gboolean get_array,
                        GValue* result)
{
	FILE* _tmp0_;
	GValue _tmp1_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (tip_message != NULL);
	g_return_if_fail (gettext_package != NULL);
	_tmp0_ = stdin;
	dh_out_read_and_output_custom (self, _g_file_stream_read_line_dh_linein_func, _tmp0_, tip_message, gettext_package, arg, validator, get_array, &_tmp1_);
	*result = _tmp1_;
	return;
}

static gint64
int64_parse (const gchar* str,
             guint _base)
{
	gint64 result;
	g_return_val_if_fail (str != NULL, 0LL);
	result = g_ascii_strtoll (str, NULL, _base);
	return result;
}

static guint64
uint64_parse (const gchar* str,
              guint _base)
{
	guint64 result;
	g_return_val_if_fail (str != NULL, 0ULL);
	result = g_ascii_strtoull (str, NULL, _base);
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static gboolean
int64_try_parse (const gchar* str,
                 gint64* _result_,
                 const gchar** unparsed,
                 guint _base)
{
	gint64 _vala__result_ = 0LL;
	const gchar* _vala_unparsed = NULL;
	gchar* endptr = NULL;
	gchar* _tmp0_ = NULL;
	gint64 _tmp1_;
	gchar* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gboolean result;
	g_return_val_if_fail (str != NULL, FALSE);
	errno = 0;
	_tmp1_ = g_ascii_strtoll (str, &_tmp0_, _base);
	endptr = _tmp0_;
	_vala__result_ = _tmp1_;
	_tmp2_ = endptr;
	_tmp3_ = strlen (str);
	_tmp4_ = _tmp3_;
	if (_tmp2_ == (((gchar*) str) + _tmp4_)) {
		gboolean _tmp5_ = FALSE;
		_vala_unparsed = "";
		if (errno != ERANGE) {
			_tmp5_ = errno != EINVAL;
		} else {
			_tmp5_ = FALSE;
		}
		result = _tmp5_;
		if (_result_) {
			*_result_ = _vala__result_;
		}
		if (unparsed) {
			*unparsed = _vala_unparsed;
		}
		return result;
	} else {
		gchar* _tmp6_;
		_tmp6_ = endptr;
		_vala_unparsed = (const gchar*) _tmp6_;
		result = FALSE;
		if (_result_) {
			*_result_ = _vala__result_;
		}
		if (unparsed) {
			*unparsed = _vala_unparsed;
		}
		return result;
	}
}

void
dh_out_read_and_output_custom (DhOut* self,
                               DhLineinFunc func,
                               gpointer func_target,
                               const gchar* tip_message,
                               const gchar* gettext_package,
                               DhArgInfo* arg,
                               DhValidator* validator,
                               gboolean get_array,
                               GValue* result)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (tip_message != NULL);
	g_return_if_fail (gettext_package != NULL);
	while (TRUE) {
		gchar* str = NULL;
		gchar* _tmp0_;
		const gchar* _tmp1_;
		g_print ("%s", g_dgettext (gettext_package, tip_message));
		_tmp0_ = func (func_target);
		str = _tmp0_;
		_tmp1_ = str;
		if (_tmp1_ == NULL) {
			GValue _tmp2_ = {0};
			g_value_init (&_tmp2_, G_TYPE_GTYPE);
			g_value_set_gtype (&_tmp2_, G_TYPE_NONE);
			*result = _tmp2_;
			_g_free0 (str);
			return;
		} else {
			if (arg != NULL) {
				const gchar* _tmp3_;
				_tmp3_ = str;
				if (g_regex_match_simple ("^\\?$", _tmp3_, 0, 0)) {
					gchar* _tmp4_;
					gchar* _tmp5_;
					_tmp4_ = dh_arg_info_help_message (arg, gettext_package);
					_tmp5_ = _tmp4_;
					g_print ("%s", _tmp5_);
					_g_free0 (_tmp5_);
					_g_free0 (str);
					continue;
				} else {
					gchar ret = '\0';
					const gchar* _tmp6_;
					_tmp6_ = str;
					ret = dh_arg_info_match_char (arg, _tmp6_);
					if (((gint) ret) != 0) {
						GValue _tmp7_ = {0};
						g_value_init (&_tmp7_, G_TYPE_CHAR);
						g_value_set_schar (&_tmp7_, ret);
						*result = _tmp7_;
						_g_free0 (str);
						return;
					}
				}
			}
			if (validator != NULL) {
				if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_INT_VALIDATOR) {
					const gchar* _tmp8_;
					_tmp8_ = str;
					if (g_regex_match_simple ("^[\\-|\\+]?[0-9]+$", _tmp8_, 0, 0)) {
						gint64 ret = 0LL;
						const gchar* _tmp9_;
						_tmp9_ = str;
						ret = int64_parse (_tmp9_, (guint) 10);
						if (dh_validator_in_field ((DhValidator*) (IS_DH_INT_VALIDATOR (validator) ? ((DhIntValidator*) validator) : NULL), &ret)) {
							GValue _tmp10_ = {0};
							g_value_init (&_tmp10_, G_TYPE_INT64);
							g_value_set_int64 (&_tmp10_, ret);
							*result = _tmp10_;
							_g_free0 (str);
							return;
						}
					}
				} else {
					if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_UINT_VALIDATOR) {
						const gchar* _tmp11_;
						_tmp11_ = str;
						if (g_regex_match_simple ("^[\\+]?[0-9]+$", _tmp11_, 0, 0)) {
							guint64 ret = 0ULL;
							const gchar* _tmp12_;
							_tmp12_ = str;
							ret = uint64_parse (_tmp12_, (guint) 10);
							if (dh_validator_in_field ((DhValidator*) (IS_DH_UINT_VALIDATOR (validator) ? ((DhUIntValidator*) validator) : NULL), &ret)) {
								GValue _tmp13_ = {0};
								g_value_init (&_tmp13_, G_TYPE_UINT64);
								g_value_set_uint64 (&_tmp13_, ret);
								*result = _tmp13_;
								_g_free0 (str);
								return;
							}
						}
					} else {
						if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_DOUBLE_VALIDATOR) {
							gchar* end_str = NULL;
							gdouble ret = 0.0;
							const gchar* _tmp14_;
							const gchar* _tmp15_ = NULL;
							gdouble _tmp16_;
							gchar* _tmp17_;
							const gchar* _tmp18_;
							_tmp14_ = str;
							_tmp16_ = g_ascii_strtod (_tmp14_, &_tmp15_);
							_g_free0 (end_str);
							_tmp17_ = g_strdup (_tmp15_);
							end_str = _tmp17_;
							ret = _tmp16_;
							_tmp18_ = end_str;
							if (g_strcmp0 (_tmp18_, "") == 0) {
								if (dh_validator_in_field ((DhValidator*) (IS_DH_DOUBLE_VALIDATOR (validator) ? ((DhDoubleValidator*) validator) : NULL), &ret)) {
									GValue _tmp19_ = {0};
									g_value_init (&_tmp19_, G_TYPE_DOUBLE);
									g_value_set_double (&_tmp19_, ret);
									*result = _tmp19_;
									_g_free0 (end_str);
									_g_free0 (str);
									return;
								}
							}
							_g_free0 (end_str);
						} else {
							if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_REGEX_VALIDATOR) {
								const gchar* _tmp20_;
								_tmp20_ = str;
								if (dh_validator_in_field ((DhValidator*) (IS_DH_REGEX_VALIDATOR (validator) ? ((DhRegexValidator*) validator) : NULL), _tmp20_)) {
									GValue _tmp21_ = {0};
									g_value_init (&_tmp21_, G_TYPE_STRING);
									g_value_take_string (&_tmp21_, str);
									*result = _tmp21_;
									return;
								}
							} else {
								if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_MATCH_VALIDATOR) {
									const gchar* _tmp22_;
									_tmp22_ = str;
									if (dh_validator_in_field ((DhValidator*) (IS_DH_MATCH_VALIDATOR (validator) ? ((DhMatchValidator*) validator) : NULL), _tmp22_)) {
										GValue _tmp23_ = {0};
										g_value_init (&_tmp23_, G_TYPE_STRING);
										g_value_take_string (&_tmp23_, str);
										*result = _tmp23_;
										return;
									}
								} else {
									if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_INT_ARRAY_VALIDATOR) {
										DhIntArrayValidator* iav = NULL;
										DhIntArrayValidator* _tmp24_;
										GList* ret = NULL;
										gchar** after_str = NULL;
										const gchar* _tmp25_;
										DhIntArrayValidator* _tmp26_;
										const gchar* _tmp27_;
										gchar** _tmp28_;
										gchar** _tmp29_;
										gint after_str_length1;
										gint _after_str_size_;
										gboolean success = FALSE;
										_tmp24_ = _g_object_ref0 (IS_DH_INT_ARRAY_VALIDATOR (validator) ? ((DhIntArrayValidator*) validator) : NULL);
										iav = _tmp24_;
										ret = NULL;
										_tmp25_ = str;
										_tmp26_ = iav;
										_tmp27_ = _tmp26_->split_str;
										_tmp29_ = _tmp28_ = g_strsplit (_tmp25_, _tmp27_, 0);
										after_str = _tmp29_;
										after_str_length1 = _vala_array_length (_tmp28_);
										_after_str_size_ = after_str_length1;
										success = TRUE;
										{
											gint i = 0;
											i = 0;
											{
												gboolean _tmp30_ = FALSE;
												_tmp30_ = TRUE;
												while (TRUE) {
													gchar** _tmp32_;
													gint _tmp32__length1;
													gint64 temp = 0LL;
													gchar** _tmp33_;
													gint _tmp33__length1;
													const gchar* _tmp34_;
													gint64 _tmp35_ = 0LL;
													gboolean _tmp36_;
													if (!_tmp30_) {
														gint _tmp31_;
														_tmp31_ = i;
														i = _tmp31_ + 1;
													}
													_tmp30_ = FALSE;
													_tmp32_ = after_str;
													_tmp32__length1 = after_str_length1;
													if (!(i < _tmp32__length1)) {
														break;
													}
													_tmp33_ = after_str;
													_tmp33__length1 = after_str_length1;
													_tmp34_ = _tmp33_[i];
													_tmp36_ = int64_try_parse (_tmp34_, &_tmp35_, NULL, (guint) 0);
													temp = _tmp35_;
													if (_tmp36_) {
														gint64* _tmp37_;
														_tmp37_ = __int64_dup0 (&temp);
														ret = g_list_append (ret, _tmp37_);
													} else {
														success = FALSE;
														break;
													}
												}
											}
										}
										if (success) {
											DhIntArrayValidator* _tmp38_;
											GList* _tmp39_;
											_tmp38_ = iav;
											_tmp39_ = ret;
											if (dh_validator_in_field ((DhValidator*) _tmp38_, _tmp39_)) {
												GValue _tmp40_ = {0};
												g_value_init (&_tmp40_, G_TYPE_POINTER);
												g_value_set_pointer (&_tmp40_, ret);
												*result = _tmp40_;
												after_str = (_vala_array_free (after_str, after_str_length1, (GDestroyNotify) g_free), NULL);
												_g_object_unref0 (iav);
												_g_free0 (str);
												return;
											}
										}
										after_str = (_vala_array_free (after_str, after_str_length1, (GDestroyNotify) g_free), NULL);
										(ret == NULL) ? NULL : (ret = (_g_list_free__g_free0_ (ret), NULL));
										_g_object_unref0 (iav);
									}
								}
							}
						}
					}
				}
			} else {
				GValue _tmp41_ = {0};
				g_value_init (&_tmp41_, G_TYPE_STRING);
				g_value_take_string (&_tmp41_, str);
				*result = _tmp41_;
				return;
			}
			g_print ("Unsuccess!\n");
		}
		_g_free0 (str);
	}
}

void
dh_out_read_and_output_as_int_custom (DhOut* self,
                                      DhLineinFunc func,
                                      gpointer func_target,
                                      const gchar* tip_message,
                                      const gchar* gettext_package,
                                      DhArgInfo* arg,
                                      gint64 min,
                                      gint64 max,
                                      gboolean get_array,
                                      GValue* result)
{
	DhIntValidator* validator = NULL;
	DhIntValidator* _tmp0_;
	GValue _tmp1_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (tip_message != NULL);
	g_return_if_fail (gettext_package != NULL);
	_tmp0_ = dh_int_validator_new (min, max);
	validator = _tmp0_;
	dh_validator_set_range ((DhValidator*) validator, &min, &max);
	dh_out_read_and_output_custom (self, func, func_target, tip_message, gettext_package, arg, (DhValidator*) validator, get_array, &_tmp1_);
	*result = _tmp1_;
	_g_object_unref0 (validator);
	return;
}

void
dh_out_read_and_output_as_int (DhOut* self,
                               const gchar* tip_message,
                               const gchar* gettext_package,
                               DhArgInfo* arg,
                               gint64 min,
                               gint64 max,
                               gboolean get_array,
                               GValue* result)
{
	FILE* _tmp0_;
	GValue _tmp1_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (tip_message != NULL);
	g_return_if_fail (gettext_package != NULL);
	_tmp0_ = stdin;
	dh_out_read_and_output_as_int_custom (self, _g_file_stream_read_line_dh_linein_func, _tmp0_, tip_message, gettext_package, arg, min, max, get_array, &_tmp1_);
	*result = _tmp1_;
	return;
}

DhOut*
dh_out_construct (GType object_type)
{
	DhOut * self = NULL;
	self = (DhOut*) g_object_new (object_type, NULL);
	return self;
}

DhOut*
dh_out_new (void)
{
	return dh_out_construct (TYPE_DH_OUT);
}

static void
dh_out_class_init (DhOutClass * klass,
                   gpointer klass_data)
{
	dh_out_parent_class = g_type_class_peek_parent (klass);
}

static void
dh_out_instance_init (DhOut * self,
                      gpointer klass)
{
}

static GType
dh_out_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhOutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_out_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhOut), 0, (GInstanceInitFunc) dh_out_instance_init, NULL };
	GType dh_out_type_id;
	dh_out_type_id = g_type_register_static (G_TYPE_OBJECT, "DhOut", &g_define_type_info, 0);
	return dh_out_type_id;
}

GType
dh_out_get_type (void)
{
	static volatile gsize dh_out_type_id__once = 0;
	if (g_once_init_enter (&dh_out_type_id__once)) {
		GType dh_out_type_id;
		dh_out_type_id = dh_out_get_type_once ();
		g_once_init_leave (&dh_out_type_id__once, dh_out_type_id);
	}
	return dh_out_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

