/* dh_validator.c generated by valac 0.56.16, the Vala compiler
 * generated from dh_validator.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_DH_VALIDATOR (dh_validator_get_type ())
#define DH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_VALIDATOR, DhValidator))
#define IS_DH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_VALIDATOR))
#define DH_VALIDATOR_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_DH_VALIDATOR, DhValidatorIface))

typedef struct _DhValidator DhValidator;
typedef struct _DhValidatorIface DhValidatorIface;

#define TYPE_DH_INT_VALIDATOR (dh_int_validator_get_type ())
#define DH_INT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_INT_VALIDATOR, DhIntValidator))
#define DH_INT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_INT_VALIDATOR, DhIntValidatorClass))
#define IS_DH_INT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_INT_VALIDATOR))
#define IS_DH_INT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_INT_VALIDATOR))
#define DH_INT_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_INT_VALIDATOR, DhIntValidatorClass))

typedef struct _DhIntValidator DhIntValidator;
typedef struct _DhIntValidatorClass DhIntValidatorClass;
typedef struct _DhIntValidatorPrivate DhIntValidatorPrivate;
enum  {
	DH_INT_VALIDATOR_0_PROPERTY,
	DH_INT_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_int_validator_properties[DH_INT_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_UINT_VALIDATOR (dh_uint_validator_get_type ())
#define DH_UINT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_UINT_VALIDATOR, DhUIntValidator))
#define DH_UINT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_UINT_VALIDATOR, DhUIntValidatorClass))
#define IS_DH_UINT_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_UINT_VALIDATOR))
#define IS_DH_UINT_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_UINT_VALIDATOR))
#define DH_UINT_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_UINT_VALIDATOR, DhUIntValidatorClass))

typedef struct _DhUIntValidator DhUIntValidator;
typedef struct _DhUIntValidatorClass DhUIntValidatorClass;
typedef struct _DhUIntValidatorPrivate DhUIntValidatorPrivate;
enum  {
	DH_UINT_VALIDATOR_0_PROPERTY,
	DH_UINT_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_uint_validator_properties[DH_UINT_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_DOUBLE_VALIDATOR (dh_double_validator_get_type ())
#define DH_DOUBLE_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidator))
#define DH_DOUBLE_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidatorClass))
#define IS_DH_DOUBLE_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_DOUBLE_VALIDATOR))
#define IS_DH_DOUBLE_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_DOUBLE_VALIDATOR))
#define DH_DOUBLE_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidatorClass))

typedef struct _DhDoubleValidator DhDoubleValidator;
typedef struct _DhDoubleValidatorClass DhDoubleValidatorClass;
typedef struct _DhDoubleValidatorPrivate DhDoubleValidatorPrivate;
enum  {
	DH_DOUBLE_VALIDATOR_0_PROPERTY,
	DH_DOUBLE_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_double_validator_properties[DH_DOUBLE_VALIDATOR_NUM_PROPERTIES];

#define TYPE_DH_REGEX_VALIDATOR (dh_regex_validator_get_type ())
#define DH_REGEX_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_REGEX_VALIDATOR, DhRegexValidator))
#define DH_REGEX_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_REGEX_VALIDATOR, DhRegexValidatorClass))
#define IS_DH_REGEX_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_REGEX_VALIDATOR))
#define IS_DH_REGEX_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_REGEX_VALIDATOR))
#define DH_REGEX_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_REGEX_VALIDATOR, DhRegexValidatorClass))

typedef struct _DhRegexValidator DhRegexValidator;
typedef struct _DhRegexValidatorClass DhRegexValidatorClass;
typedef struct _DhRegexValidatorPrivate DhRegexValidatorPrivate;
enum  {
	DH_REGEX_VALIDATOR_0_PROPERTY,
	DH_REGEX_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_regex_validator_properties[DH_REGEX_VALIDATOR_NUM_PROPERTIES];
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

#define TYPE_DH_MATCH_VALIDATOR (dh_match_validator_get_type ())
#define DH_MATCH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_MATCH_VALIDATOR, DhMatchValidator))
#define DH_MATCH_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_MATCH_VALIDATOR, DhMatchValidatorClass))
#define IS_DH_MATCH_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_MATCH_VALIDATOR))
#define IS_DH_MATCH_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_MATCH_VALIDATOR))
#define DH_MATCH_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_MATCH_VALIDATOR, DhMatchValidatorClass))

typedef struct _DhMatchValidator DhMatchValidator;
typedef struct _DhMatchValidatorClass DhMatchValidatorClass;
typedef struct _DhMatchValidatorPrivate DhMatchValidatorPrivate;
enum  {
	DH_MATCH_VALIDATOR_0_PROPERTY,
	DH_MATCH_VALIDATOR_NUM_PROPERTIES
};
static GParamSpec* dh_match_validator_properties[DH_MATCH_VALIDATOR_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_DH_ARG_INFO (dh_arg_info_get_type ())
#define DH_ARG_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_ARG_INFO, DhArgInfo))
#define DH_ARG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_ARG_INFO, DhArgInfoClass))
#define IS_DH_ARG_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_ARG_INFO))
#define IS_DH_ARG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_ARG_INFO))
#define DH_ARG_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_ARG_INFO, DhArgInfoClass))

typedef struct _DhArgInfo DhArgInfo;
typedef struct _DhArgInfoClass DhArgInfoClass;
typedef struct _DhArgInfoPrivate DhArgInfoPrivate;
enum  {
	DH_ARG_INFO_0_PROPERTY,
	DH_ARG_INFO_NUM_PROPERTIES
};
static GParamSpec* dh_arg_info_properties[DH_ARG_INFO_NUM_PROPERTIES];

#define TYPE_DH_OUT (dh_out_get_type ())
#define DH_OUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DH_OUT, DhOut))
#define DH_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DH_OUT, DhOutClass))
#define IS_DH_OUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DH_OUT))
#define IS_DH_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DH_OUT))
#define DH_OUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DH_OUT, DhOutClass))

typedef struct _DhOut DhOut;
typedef struct _DhOutClass DhOutClass;
typedef struct _DhOutPrivate DhOutPrivate;
enum  {
	DH_OUT_0_PROPERTY,
	DH_OUT_NUM_PROPERTIES
};
static GParamSpec* dh_out_properties[DH_OUT_NUM_PROPERTIES];
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

struct _DhValidatorIface {
	GTypeInterface parent_iface;
	gboolean (*in_field) (DhValidator* self, gconstpointer val);
	void (*set_range) (DhValidator* self, gconstpointer min_val, gconstpointer max_val);
};

struct _DhIntValidator {
	GObject parent_instance;
	DhIntValidatorPrivate * priv;
};

struct _DhIntValidatorClass {
	GObjectClass parent_class;
};

struct _DhIntValidatorPrivate {
	gint64 min;
	gint64 max;
};

struct _DhUIntValidator {
	GObject parent_instance;
	DhUIntValidatorPrivate * priv;
};

struct _DhUIntValidatorClass {
	GObjectClass parent_class;
};

struct _DhUIntValidatorPrivate {
	guint64 min;
	guint64 max;
};

struct _DhDoubleValidator {
	GObject parent_instance;
	DhDoubleValidatorPrivate * priv;
};

struct _DhDoubleValidatorClass {
	GObjectClass parent_class;
};

struct _DhDoubleValidatorPrivate {
	gdouble min;
	gdouble max;
};

struct _DhRegexValidator {
	GObject parent_instance;
	DhRegexValidatorPrivate * priv;
};

struct _DhRegexValidatorClass {
	GObjectClass parent_class;
};

struct _DhRegexValidatorPrivate {
	GRegex* reg;
};

struct _DhMatchValidator {
	GObject parent_instance;
	DhMatchValidatorPrivate * priv;
};

struct _DhMatchValidatorClass {
	GObjectClass parent_class;
};

struct _DhMatchValidatorPrivate {
	gchar* match_str;
};

struct _DhArgInfo {
	GObject parent_instance;
	DhArgInfoPrivate * priv;
};

struct _DhArgInfoClass {
	GObjectClass parent_class;
};

struct _DhArgInfoPrivate {
	GList* arg;
	GList* arg_fullname;
	GList* description;
};

struct _DhOut {
	GObject parent_instance;
	DhOutPrivate * priv;
};

struct _DhOutClass {
	GObjectClass parent_class;
};

static gint DhIntValidator_private_offset;
static gpointer dh_int_validator_parent_class = NULL;
static DhValidatorIface * dh_int_validator_dh_validator_parent_iface = NULL;
static gint DhUIntValidator_private_offset;
static gpointer dh_uint_validator_parent_class = NULL;
static DhValidatorIface * dh_uint_validator_dh_validator_parent_iface = NULL;
static gint DhDoubleValidator_private_offset;
static gpointer dh_double_validator_parent_class = NULL;
static DhValidatorIface * dh_double_validator_dh_validator_parent_iface = NULL;
static gint DhRegexValidator_private_offset;
static gpointer dh_regex_validator_parent_class = NULL;
static DhValidatorIface * dh_regex_validator_dh_validator_parent_iface = NULL;
static gint DhMatchValidator_private_offset;
static gpointer dh_match_validator_parent_class = NULL;
static DhValidatorIface * dh_match_validator_dh_validator_parent_iface = NULL;
static gint DhArgInfo_private_offset;
static gpointer dh_arg_info_parent_class = NULL;
static gpointer dh_out_parent_class = NULL;

VALA_EXTERN GType dh_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhValidator, g_object_unref)
VALA_EXTERN gboolean dh_validator_in_field (DhValidator* self,
                                gconstpointer val);
VALA_EXTERN void dh_validator_set_range (DhValidator* self,
                             gconstpointer min_val,
                             gconstpointer max_val);
static GType dh_validator_get_type_once (void);
VALA_EXTERN GType dh_int_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhIntValidator, g_object_unref)
static gboolean dh_int_validator_real_in_field (DhValidator* base,
                                         gint64* val);
static void dh_int_validator_real_set_range (DhValidator* base,
                                      gint64* min_val,
                                      gint64* max_val);
VALA_EXTERN DhIntValidator* dh_int_validator_new (void);
VALA_EXTERN DhIntValidator* dh_int_validator_construct (GType object_type);
static void dh_int_validator_finalize (GObject * obj);
static GType dh_int_validator_get_type_once (void);
VALA_EXTERN GType dh_uint_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhUIntValidator, g_object_unref)
static gboolean dh_uint_validator_real_in_field (DhValidator* base,
                                          guint64* val);
static void dh_uint_validator_real_set_range (DhValidator* base,
                                       guint64* min_val,
                                       guint64* max_val);
VALA_EXTERN DhUIntValidator* dh_uint_validator_new (void);
VALA_EXTERN DhUIntValidator* dh_uint_validator_construct (GType object_type);
static void dh_uint_validator_finalize (GObject * obj);
static GType dh_uint_validator_get_type_once (void);
VALA_EXTERN GType dh_double_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhDoubleValidator, g_object_unref)
static gboolean dh_double_validator_real_in_field (DhValidator* base,
                                            gdouble* val);
static void dh_double_validator_real_set_range (DhValidator* base,
                                         gdouble* min_val,
                                         gdouble* max_val);
VALA_EXTERN DhDoubleValidator* dh_double_validator_new (void);
VALA_EXTERN DhDoubleValidator* dh_double_validator_construct (GType object_type);
static void dh_double_validator_finalize (GObject * obj);
static GType dh_double_validator_get_type_once (void);
VALA_EXTERN GType dh_regex_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhRegexValidator, g_object_unref)
static gboolean dh_regex_validator_real_in_field (DhValidator* base,
                                           const gchar* val);
static void dh_regex_validator_real_set_range (DhValidator* base,
                                        GRegex* min_val,
                                        GRegex* max_val);
VALA_EXTERN DhRegexValidator* dh_regex_validator_new (void);
VALA_EXTERN DhRegexValidator* dh_regex_validator_construct (GType object_type);
static void dh_regex_validator_finalize (GObject * obj);
static GType dh_regex_validator_get_type_once (void);
VALA_EXTERN GType dh_match_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhMatchValidator, g_object_unref)
static gboolean dh_match_validator_real_in_field (DhValidator* base,
                                           const gchar* val);
static void dh_match_validator_real_set_range (DhValidator* base,
                                        const gchar* min_val,
                                        const gchar* max_val);
VALA_EXTERN DhMatchValidator* dh_match_validator_new (void);
VALA_EXTERN DhMatchValidator* dh_match_validator_construct (GType object_type);
static void dh_match_validator_finalize (GObject * obj);
static GType dh_match_validator_get_type_once (void);
VALA_EXTERN GType dh_arg_info_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhArgInfo, g_object_unref)
static void _g_free0_ (gpointer var);
static inline void _g_list_free__g_free0_ (GList* self);
VALA_EXTERN void dh_arg_info_add_arg (DhArgInfo* self,
                          gchar new_arg,
                          const gchar* new_arg_fullname,
                          const gchar* new_description);
VALA_EXTERN gchar* dh_arg_info_help_message (DhArgInfo* self,
                                 const gchar* gettext_package);
VALA_EXTERN gchar dh_arg_info_match_char (DhArgInfo* self,
                              const gchar* str);
VALA_EXTERN DhArgInfo* dh_arg_info_new (void);
VALA_EXTERN DhArgInfo* dh_arg_info_construct (GType object_type);
static void dh_arg_info_finalize (GObject * obj);
static GType dh_arg_info_get_type_once (void);
VALA_EXTERN GType dh_out_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DhOut, g_object_unref)
VALA_EXTERN void dh_out_read_and_output (DhOut* self,
                             const gchar* tip_message,
                             const gchar* gettext_package,
                             DhArgInfo* arg,
                             DhValidator* validator,
                             GValue* result);
VALA_EXTERN DhOut* dh_out_new (void);
VALA_EXTERN DhOut* dh_out_construct (GType object_type);
static GType dh_out_get_type_once (void);

gboolean
dh_validator_in_field (DhValidator* self,
                       gconstpointer val)
{
	DhValidatorIface* _iface_;
	g_return_val_if_fail (self != NULL, FALSE);
	_iface_ = DH_VALIDATOR_GET_INTERFACE (self);
	if (_iface_->in_field) {
		return _iface_->in_field (self, val);
	}
	return FALSE;
}

void
dh_validator_set_range (DhValidator* self,
                        gconstpointer min_val,
                        gconstpointer max_val)
{
	DhValidatorIface* _iface_;
	g_return_if_fail (self != NULL);
	_iface_ = DH_VALIDATOR_GET_INTERFACE (self);
	if (_iface_->set_range) {
		_iface_->set_range (self, min_val, max_val);
	}
}

static void
dh_validator_default_init (DhValidatorIface * iface,
                           gpointer iface_data)
{
}

static GType
dh_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhValidatorIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_validator_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType dh_validator_type_id;
	dh_validator_type_id = g_type_register_static (G_TYPE_INTERFACE, "DhValidator", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (dh_validator_type_id, G_TYPE_OBJECT);
	return dh_validator_type_id;
}

GType
dh_validator_get_type (void)
{
	static volatile gsize dh_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_validator_type_id__once)) {
		GType dh_validator_type_id;
		dh_validator_type_id = dh_validator_get_type_once ();
		g_once_init_leave (&dh_validator_type_id__once, dh_validator_type_id);
	}
	return dh_validator_type_id__once;
}

static inline gpointer
dh_int_validator_get_instance_private (DhIntValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhIntValidator_private_offset);
}

static gboolean
dh_int_validator_real_in_field (DhValidator* base,
                                gint64* val)
{
	DhIntValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhIntValidator*) base;
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_int_validator_real_set_range (DhValidator* base,
                                 gint64* min_val,
                                 gint64* max_val)
{
	DhIntValidator * self;
	self = (DhIntValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

DhIntValidator*
dh_int_validator_construct (GType object_type)
{
	DhIntValidator * self = NULL;
	self = (DhIntValidator*) g_object_new (object_type, NULL);
	return self;
}

DhIntValidator*
dh_int_validator_new (void)
{
	return dh_int_validator_construct (TYPE_DH_INT_VALIDATOR);
}

static void
dh_int_validator_class_init (DhIntValidatorClass * klass,
                             gpointer klass_data)
{
	dh_int_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhIntValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_int_validator_finalize;
}

static void
dh_int_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                              gpointer iface_data)
{
	dh_int_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_int_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_int_validator_real_set_range;
}

static void
dh_int_validator_instance_init (DhIntValidator * self,
                                gpointer klass)
{
	self->priv = dh_int_validator_get_instance_private (self);
}

static void
dh_int_validator_finalize (GObject * obj)
{
	DhIntValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_INT_VALIDATOR, DhIntValidator);
	G_OBJECT_CLASS (dh_int_validator_parent_class)->finalize (obj);
}

static GType
dh_int_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhIntValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_int_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhIntValidator), 0, (GInstanceInitFunc) dh_int_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_int_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_int_validator_type_id;
	dh_int_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhIntValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_int_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhIntValidator_private_offset = g_type_add_instance_private (dh_int_validator_type_id, sizeof (DhIntValidatorPrivate));
	return dh_int_validator_type_id;
}

GType
dh_int_validator_get_type (void)
{
	static volatile gsize dh_int_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_int_validator_type_id__once)) {
		GType dh_int_validator_type_id;
		dh_int_validator_type_id = dh_int_validator_get_type_once ();
		g_once_init_leave (&dh_int_validator_type_id__once, dh_int_validator_type_id);
	}
	return dh_int_validator_type_id__once;
}

static inline gpointer
dh_uint_validator_get_instance_private (DhUIntValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhUIntValidator_private_offset);
}

static gboolean
dh_uint_validator_real_in_field (DhValidator* base,
                                 guint64* val)
{
	DhUIntValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhUIntValidator*) base;
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_uint_validator_real_set_range (DhValidator* base,
                                  guint64* min_val,
                                  guint64* max_val)
{
	DhUIntValidator * self;
	self = (DhUIntValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

DhUIntValidator*
dh_uint_validator_construct (GType object_type)
{
	DhUIntValidator * self = NULL;
	self = (DhUIntValidator*) g_object_new (object_type, NULL);
	return self;
}

DhUIntValidator*
dh_uint_validator_new (void)
{
	return dh_uint_validator_construct (TYPE_DH_UINT_VALIDATOR);
}

static void
dh_uint_validator_class_init (DhUIntValidatorClass * klass,
                              gpointer klass_data)
{
	dh_uint_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhUIntValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_uint_validator_finalize;
}

static void
dh_uint_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                               gpointer iface_data)
{
	dh_uint_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_uint_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_uint_validator_real_set_range;
}

static void
dh_uint_validator_instance_init (DhUIntValidator * self,
                                 gpointer klass)
{
	self->priv = dh_uint_validator_get_instance_private (self);
}

static void
dh_uint_validator_finalize (GObject * obj)
{
	DhUIntValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_UINT_VALIDATOR, DhUIntValidator);
	G_OBJECT_CLASS (dh_uint_validator_parent_class)->finalize (obj);
}

static GType
dh_uint_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhUIntValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_uint_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhUIntValidator), 0, (GInstanceInitFunc) dh_uint_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_uint_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_uint_validator_type_id;
	dh_uint_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhUIntValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_uint_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhUIntValidator_private_offset = g_type_add_instance_private (dh_uint_validator_type_id, sizeof (DhUIntValidatorPrivate));
	return dh_uint_validator_type_id;
}

GType
dh_uint_validator_get_type (void)
{
	static volatile gsize dh_uint_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_uint_validator_type_id__once)) {
		GType dh_uint_validator_type_id;
		dh_uint_validator_type_id = dh_uint_validator_get_type_once ();
		g_once_init_leave (&dh_uint_validator_type_id__once, dh_uint_validator_type_id);
	}
	return dh_uint_validator_type_id__once;
}

static inline gpointer
dh_double_validator_get_instance_private (DhDoubleValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhDoubleValidator_private_offset);
}

static gboolean
dh_double_validator_real_in_field (DhValidator* base,
                                   gdouble* val)
{
	DhDoubleValidator * self;
	gboolean _tmp0_ = FALSE;
	gboolean result;
	self = (DhDoubleValidator*) base;
	if ((*val) >= self->priv->min) {
		_tmp0_ = (*val) <= self->priv->max;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
dh_double_validator_real_set_range (DhValidator* base,
                                    gdouble* min_val,
                                    gdouble* max_val)
{
	DhDoubleValidator * self;
	self = (DhDoubleValidator*) base;
	if ((*min_val) > (*max_val)) {
		self->priv->min = *max_val;
		self->priv->max = *min_val;
	} else {
		self->priv->min = *min_val;
		self->priv->max = *max_val;
	}
}

DhDoubleValidator*
dh_double_validator_construct (GType object_type)
{
	DhDoubleValidator * self = NULL;
	self = (DhDoubleValidator*) g_object_new (object_type, NULL);
	return self;
}

DhDoubleValidator*
dh_double_validator_new (void)
{
	return dh_double_validator_construct (TYPE_DH_DOUBLE_VALIDATOR);
}

static void
dh_double_validator_class_init (DhDoubleValidatorClass * klass,
                                gpointer klass_data)
{
	dh_double_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhDoubleValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_double_validator_finalize;
}

static void
dh_double_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                 gpointer iface_data)
{
	dh_double_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_double_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_double_validator_real_set_range;
}

static void
dh_double_validator_instance_init (DhDoubleValidator * self,
                                   gpointer klass)
{
	self->priv = dh_double_validator_get_instance_private (self);
}

static void
dh_double_validator_finalize (GObject * obj)
{
	DhDoubleValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_DOUBLE_VALIDATOR, DhDoubleValidator);
	G_OBJECT_CLASS (dh_double_validator_parent_class)->finalize (obj);
}

static GType
dh_double_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhDoubleValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_double_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhDoubleValidator), 0, (GInstanceInitFunc) dh_double_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_double_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_double_validator_type_id;
	dh_double_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhDoubleValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_double_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhDoubleValidator_private_offset = g_type_add_instance_private (dh_double_validator_type_id, sizeof (DhDoubleValidatorPrivate));
	return dh_double_validator_type_id;
}

GType
dh_double_validator_get_type (void)
{
	static volatile gsize dh_double_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_double_validator_type_id__once)) {
		GType dh_double_validator_type_id;
		dh_double_validator_type_id = dh_double_validator_get_type_once ();
		g_once_init_leave (&dh_double_validator_type_id__once, dh_double_validator_type_id);
	}
	return dh_double_validator_type_id__once;
}

static inline gpointer
dh_regex_validator_get_instance_private (DhRegexValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhRegexValidator_private_offset);
}

static gboolean
dh_regex_validator_real_in_field (DhValidator* base,
                                  const gchar* val)
{
	DhRegexValidator * self;
	GRegex* _tmp0_;
	gboolean result;
	self = (DhRegexValidator*) base;
	g_return_val_if_fail (val != NULL, FALSE);
	_tmp0_ = self->priv->reg;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		GRegex* _tmp1_;
		_tmp1_ = self->priv->reg;
		result = g_regex_match (_tmp1_, val, 0, NULL);
		return result;
	}
}

static gpointer
_g_regex_ref0 (gpointer self)
{
	return self ? g_regex_ref (self) : NULL;
}

static void
dh_regex_validator_real_set_range (DhValidator* base,
                                   GRegex* min_val,
                                   GRegex* max_val)
{
	DhRegexValidator * self;
	self = (DhRegexValidator*) base;
	if (min_val != NULL) {
		GRegex* _tmp0_;
		_tmp0_ = _g_regex_ref0 (min_val);
		_g_regex_unref0 (self->priv->reg);
		self->priv->reg = _tmp0_;
	} else {
		GRegex* _tmp1_;
		_tmp1_ = _g_regex_ref0 (max_val);
		_g_regex_unref0 (self->priv->reg);
		self->priv->reg = _tmp1_;
	}
}

DhRegexValidator*
dh_regex_validator_construct (GType object_type)
{
	DhRegexValidator * self = NULL;
	self = (DhRegexValidator*) g_object_new (object_type, NULL);
	return self;
}

DhRegexValidator*
dh_regex_validator_new (void)
{
	return dh_regex_validator_construct (TYPE_DH_REGEX_VALIDATOR);
}

static void
dh_regex_validator_class_init (DhRegexValidatorClass * klass,
                               gpointer klass_data)
{
	dh_regex_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhRegexValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_regex_validator_finalize;
}

static void
dh_regex_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                gpointer iface_data)
{
	dh_regex_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_regex_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_regex_validator_real_set_range;
}

static void
dh_regex_validator_instance_init (DhRegexValidator * self,
                                  gpointer klass)
{
	self->priv = dh_regex_validator_get_instance_private (self);
}

static void
dh_regex_validator_finalize (GObject * obj)
{
	DhRegexValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_REGEX_VALIDATOR, DhRegexValidator);
	_g_regex_unref0 (self->priv->reg);
	G_OBJECT_CLASS (dh_regex_validator_parent_class)->finalize (obj);
}

static GType
dh_regex_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhRegexValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_regex_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhRegexValidator), 0, (GInstanceInitFunc) dh_regex_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_regex_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_regex_validator_type_id;
	dh_regex_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhRegexValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_regex_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhRegexValidator_private_offset = g_type_add_instance_private (dh_regex_validator_type_id, sizeof (DhRegexValidatorPrivate));
	return dh_regex_validator_type_id;
}

GType
dh_regex_validator_get_type (void)
{
	static volatile gsize dh_regex_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_regex_validator_type_id__once)) {
		GType dh_regex_validator_type_id;
		dh_regex_validator_type_id = dh_regex_validator_get_type_once ();
		g_once_init_leave (&dh_regex_validator_type_id__once, dh_regex_validator_type_id);
	}
	return dh_regex_validator_type_id__once;
}

static inline gpointer
dh_match_validator_get_instance_private (DhMatchValidator* self)
{
	return G_STRUCT_MEMBER_P (self, DhMatchValidator_private_offset);
}

static gboolean
dh_match_validator_real_in_field (DhValidator* base,
                                  const gchar* val)
{
	DhMatchValidator * self;
	const gchar* _tmp0_;
	gboolean result;
	self = (DhMatchValidator*) base;
	g_return_val_if_fail (val != NULL, FALSE);
	_tmp0_ = self->priv->match_str;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		const gchar* _tmp1_;
		_tmp1_ = self->priv->match_str;
		result = g_regex_match_simple (_tmp1_, val, 0, 0);
		return result;
	}
}

static void
dh_match_validator_real_set_range (DhValidator* base,
                                   const gchar* min_val,
                                   const gchar* max_val)
{
	DhMatchValidator * self;
	self = (DhMatchValidator*) base;
	g_return_if_fail (min_val != NULL);
	g_return_if_fail (max_val != NULL);
	if (min_val != NULL) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (min_val);
		_g_free0 (self->priv->match_str);
		self->priv->match_str = _tmp0_;
	} else {
		gchar* _tmp1_;
		_tmp1_ = g_strdup (max_val);
		_g_free0 (self->priv->match_str);
		self->priv->match_str = _tmp1_;
	}
}

DhMatchValidator*
dh_match_validator_construct (GType object_type)
{
	DhMatchValidator * self = NULL;
	self = (DhMatchValidator*) g_object_new (object_type, NULL);
	return self;
}

DhMatchValidator*
dh_match_validator_new (void)
{
	return dh_match_validator_construct (TYPE_DH_MATCH_VALIDATOR);
}

static void
dh_match_validator_class_init (DhMatchValidatorClass * klass,
                               gpointer klass_data)
{
	dh_match_validator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhMatchValidator_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_match_validator_finalize;
}

static void
dh_match_validator_dh_validator_interface_init (DhValidatorIface * iface,
                                                gpointer iface_data)
{
	dh_match_validator_dh_validator_parent_iface = g_type_interface_peek_parent (iface);
	iface->in_field = (gboolean (*) (DhValidator*, gconstpointer)) dh_match_validator_real_in_field;
	iface->set_range = (void (*) (DhValidator*, gconstpointer, gconstpointer)) dh_match_validator_real_set_range;
}

static void
dh_match_validator_instance_init (DhMatchValidator * self,
                                  gpointer klass)
{
	self->priv = dh_match_validator_get_instance_private (self);
}

static void
dh_match_validator_finalize (GObject * obj)
{
	DhMatchValidator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_MATCH_VALIDATOR, DhMatchValidator);
	_g_free0 (self->priv->match_str);
	G_OBJECT_CLASS (dh_match_validator_parent_class)->finalize (obj);
}

static GType
dh_match_validator_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhMatchValidatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_match_validator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhMatchValidator), 0, (GInstanceInitFunc) dh_match_validator_instance_init, NULL };
	static const GInterfaceInfo dh_validator_info = { (GInterfaceInitFunc) dh_match_validator_dh_validator_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType dh_match_validator_type_id;
	dh_match_validator_type_id = g_type_register_static (G_TYPE_OBJECT, "DhMatchValidator", &g_define_type_info, 0);
	g_type_add_interface_static (dh_match_validator_type_id, TYPE_DH_VALIDATOR, &dh_validator_info);
	DhMatchValidator_private_offset = g_type_add_instance_private (dh_match_validator_type_id, sizeof (DhMatchValidatorPrivate));
	return dh_match_validator_type_id;
}

GType
dh_match_validator_get_type (void)
{
	static volatile gsize dh_match_validator_type_id__once = 0;
	if (g_once_init_enter (&dh_match_validator_type_id__once)) {
		GType dh_match_validator_type_id;
		dh_match_validator_type_id = dh_match_validator_get_type_once ();
		g_once_init_leave (&dh_match_validator_type_id__once, dh_match_validator_type_id);
	}
	return dh_match_validator_type_id__once;
}

static inline gpointer
dh_arg_info_get_instance_private (DhArgInfo* self)
{
	return G_STRUCT_MEMBER_P (self, DhArgInfo_private_offset);
}

static void
_g_free0_ (gpointer var)
{
	var = (g_free (var), NULL);
}

static inline void
_g_list_free__g_free0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_free0_);
}

void
dh_arg_info_add_arg (DhArgInfo* self,
                     gchar new_arg,
                     const gchar* new_arg_fullname,
                     const gchar* new_description)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (new_arg_fullname != NULL);
	g_return_if_fail (new_description != NULL);
	self->priv->arg = g_list_append (self->priv->arg, (gpointer) ((gintptr) new_arg));
	_tmp0_ = g_strdup (new_arg_fullname);
	self->priv->arg_fullname = g_list_append (self->priv->arg_fullname, _tmp0_);
	_tmp1_ = g_strdup (new_description);
	self->priv->description = g_list_append (self->priv->description, _tmp1_);
}

gchar*
dh_arg_info_help_message (DhArgInfo* self,
                          const gchar* gettext_package)
{
	gchar* str = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (gettext_package != NULL, NULL);
	_tmp0_ = g_strdup (_ ("The arguments are:\n"));
	str = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				GList* _tmp3_;
				const gchar* _tmp4_;
				gchar* _tmp5_;
				gchar* temp_str = NULL;
				GList* _tmp6_;
				gconstpointer _tmp7_;
				gchar* _tmp8_;
				const gchar* _tmp9_;
				const gchar* _tmp10_;
				gchar* _tmp11_;
				const gchar* _tmp12_;
				gchar* _tmp13_;
				const gchar* _tmp14_;
				GList* _tmp15_;
				gconstpointer _tmp16_;
				gchar* _tmp17_;
				const gchar* _tmp18_;
				gchar* _tmp19_;
				const gchar* _tmp20_;
				GList* _tmp21_;
				gconstpointer _tmp22_;
				gchar* _tmp23_;
				const gchar* _tmp24_;
				gchar* _tmp25_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = self->priv->arg;
				if (!(((guint) i) < g_list_length (_tmp3_))) {
					break;
				}
				_tmp4_ = str;
				_tmp5_ = g_strconcat (_tmp4_, "\"", NULL);
				_g_free0 (str);
				str = _tmp5_;
				_tmp6_ = self->priv->arg;
				_tmp7_ = g_list_nth_data (_tmp6_, (guint) i);
				_tmp8_ = g_strnfill ((gsize) 1, (gchar) ((gintptr) _tmp7_));
				temp_str = _tmp8_;
				_tmp9_ = str;
				_tmp10_ = temp_str;
				_tmp11_ = g_strconcat (_tmp9_, _tmp10_, NULL);
				_g_free0 (str);
				str = _tmp11_;
				_tmp12_ = str;
				_tmp13_ = g_strconcat (_tmp12_, "\", \"", NULL);
				_g_free0 (str);
				str = _tmp13_;
				_tmp14_ = str;
				_tmp15_ = self->priv->arg_fullname;
				_tmp16_ = g_list_nth_data (_tmp15_, (guint) i);
				_tmp17_ = g_strconcat (_tmp14_, (const gchar*) _tmp16_, NULL);
				_g_free0 (str);
				str = _tmp17_;
				_tmp18_ = str;
				_tmp19_ = g_strconcat (_tmp18_, "\", \"", NULL);
				_g_free0 (str);
				str = _tmp19_;
				_tmp20_ = str;
				_tmp21_ = self->priv->description;
				_tmp22_ = g_list_nth_data (_tmp21_, (guint) i);
				_tmp23_ = g_strconcat (_tmp20_, g_dgettext (gettext_package, (const gchar*) _tmp22_), NULL);
				_g_free0 (str);
				str = _tmp23_;
				_tmp24_ = str;
				_tmp25_ = g_strconcat (_tmp24_, "\"\n", NULL);
				_g_free0 (str);
				str = _tmp25_;
				_g_free0 (temp_str);
			}
		}
	}
	result = str;
	return result;
}

gchar
dh_arg_info_match_char (DhArgInfo* self,
                        const gchar* str)
{
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	g_return_val_if_fail (str != NULL, '\0');
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				GList* _tmp2_;
				gchar* match_str = NULL;
				gchar* _tmp3_;
				const gchar* _tmp4_;
				GList* _tmp5_;
				gconstpointer _tmp6_;
				gchar* _tmp7_;
				const gchar* _tmp8_;
				gchar* _tmp11_;
				const gchar* _tmp12_;
				GList* _tmp13_;
				gconstpointer _tmp14_;
				gchar* _tmp15_;
				const gchar* _tmp16_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = self->priv->arg;
				if (!(((guint) i) < g_list_length (_tmp2_))) {
					break;
				}
				_tmp3_ = g_strdup ("^%c$");
				match_str = _tmp3_;
				_tmp4_ = match_str;
				_tmp5_ = self->priv->arg;
				_tmp6_ = g_list_nth_data (_tmp5_, (guint) i);
				_tmp7_ = g_strdup_printf (_tmp4_, (gchar) ((gintptr) _tmp6_));
				_g_free0 (match_str);
				match_str = _tmp7_;
				_tmp8_ = match_str;
				if (g_regex_match_simple (_tmp8_, str, 0, 0)) {
					GList* _tmp9_;
					gconstpointer _tmp10_;
					_tmp9_ = self->priv->arg;
					_tmp10_ = g_list_nth_data (_tmp9_, (guint) i);
					result = (gchar) ((gintptr) _tmp10_);
					_g_free0 (match_str);
					return result;
				}
				_tmp11_ = g_strdup ("^%s$");
				_g_free0 (match_str);
				match_str = _tmp11_;
				_tmp12_ = match_str;
				_tmp13_ = self->priv->arg_fullname;
				_tmp14_ = g_list_nth_data (_tmp13_, (guint) i);
				_tmp15_ = g_strdup_printf (_tmp12_, (const gchar*) _tmp14_);
				_g_free0 (match_str);
				match_str = _tmp15_;
				_tmp16_ = match_str;
				if (g_regex_match_simple (_tmp16_, str, 0, 0)) {
					GList* _tmp17_;
					gconstpointer _tmp18_;
					_tmp17_ = self->priv->arg;
					_tmp18_ = g_list_nth_data (_tmp17_, (guint) i);
					result = (gchar) ((gintptr) _tmp18_);
					_g_free0 (match_str);
					return result;
				}
				_g_free0 (match_str);
			}
		}
	}
	result = (gchar) 0;
	return result;
}

DhArgInfo*
dh_arg_info_construct (GType object_type)
{
	DhArgInfo * self = NULL;
	self = (DhArgInfo*) g_object_new (object_type, NULL);
	return self;
}

DhArgInfo*
dh_arg_info_new (void)
{
	return dh_arg_info_construct (TYPE_DH_ARG_INFO);
}

static void
dh_arg_info_class_init (DhArgInfoClass * klass,
                        gpointer klass_data)
{
	dh_arg_info_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &DhArgInfo_private_offset);
	G_OBJECT_CLASS (klass)->finalize = dh_arg_info_finalize;
}

static void
dh_arg_info_instance_init (DhArgInfo * self,
                           gpointer klass)
{
	self->priv = dh_arg_info_get_instance_private (self);
}

static void
dh_arg_info_finalize (GObject * obj)
{
	DhArgInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DH_ARG_INFO, DhArgInfo);
	(self->priv->arg == NULL) ? NULL : (self->priv->arg = (g_list_free (self->priv->arg), NULL));
	(self->priv->arg_fullname == NULL) ? NULL : (self->priv->arg_fullname = (_g_list_free__g_free0_ (self->priv->arg_fullname), NULL));
	(self->priv->description == NULL) ? NULL : (self->priv->description = (_g_list_free__g_free0_ (self->priv->description), NULL));
	G_OBJECT_CLASS (dh_arg_info_parent_class)->finalize (obj);
}

static GType
dh_arg_info_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhArgInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_arg_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhArgInfo), 0, (GInstanceInitFunc) dh_arg_info_instance_init, NULL };
	GType dh_arg_info_type_id;
	dh_arg_info_type_id = g_type_register_static (G_TYPE_OBJECT, "DhArgInfo", &g_define_type_info, 0);
	DhArgInfo_private_offset = g_type_add_instance_private (dh_arg_info_type_id, sizeof (DhArgInfoPrivate));
	return dh_arg_info_type_id;
}

GType
dh_arg_info_get_type (void)
{
	static volatile gsize dh_arg_info_type_id__once = 0;
	if (g_once_init_enter (&dh_arg_info_type_id__once)) {
		GType dh_arg_info_type_id;
		dh_arg_info_type_id = dh_arg_info_get_type_once ();
		g_once_init_leave (&dh_arg_info_type_id__once, dh_arg_info_type_id);
	}
	return dh_arg_info_type_id__once;
}

static gchar*
g_file_stream_read_line (FILE* self)
{
	gint c = 0;
	GString* ret = NULL;
	GString* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	ret = NULL;
	while (TRUE) {
		GString* _tmp0_;
		GString* _tmp2_;
		c = fgetc (self);
		if (!(c != EOF)) {
			break;
		}
		_tmp0_ = ret;
		if (_tmp0_ == NULL) {
			GString* _tmp1_;
			_tmp1_ = g_string_new ("");
			_g_string_free0 (ret);
			ret = _tmp1_;
		}
		if (c == ((gint) '\n')) {
			break;
		}
		_tmp2_ = ret;
		g_string_append_c ((GString*) _tmp2_, (gchar) c);
	}
	_tmp3_ = ret;
	if (_tmp3_ == NULL) {
		result = NULL;
		_g_string_free0 (ret);
		return result;
	} else {
		GString* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = ret;
		_tmp5_ = ((GString*) _tmp4_)->str;
		_tmp6_ = g_strdup (_tmp5_);
		result = _tmp6_;
		_g_string_free0 (ret);
		return result;
	}
}

static gint64
int64_parse (const gchar* str,
             guint _base)
{
	gint64 result;
	g_return_val_if_fail (str != NULL, 0LL);
	result = g_ascii_strtoll (str, NULL, _base);
	return result;
}

static guint64
uint64_parse (const gchar* str,
              guint _base)
{
	guint64 result;
	g_return_val_if_fail (str != NULL, 0ULL);
	result = g_ascii_strtoull (str, NULL, _base);
	return result;
}

void
dh_out_read_and_output (DhOut* self,
                        const gchar* tip_message,
                        const gchar* gettext_package,
                        DhArgInfo* arg,
                        DhValidator* validator,
                        GValue* result)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (tip_message != NULL);
	g_return_if_fail (gettext_package != NULL);
	g_return_if_fail (validator != NULL);
	while (TRUE) {
		gchar* str = NULL;
		FILE* _tmp0_;
		gchar* _tmp1_;
		const gchar* _tmp2_;
		g_print ("%s", g_dgettext (gettext_package, tip_message));
		_tmp0_ = stdin;
		_tmp1_ = g_file_stream_read_line (_tmp0_);
		str = _tmp1_;
		_tmp2_ = str;
		if (_tmp2_ == NULL) {
			GValue _tmp3_ = {0};
			g_value_init (&_tmp3_, G_TYPE_GTYPE);
			g_value_set_gtype (&_tmp3_, G_TYPE_NONE);
			*result = _tmp3_;
			_g_free0 (str);
			return;
		} else {
			if (arg != NULL) {
				const gchar* _tmp4_;
				_tmp4_ = str;
				if (g_regex_match_simple ("^\\?$", _tmp4_, 0, 0)) {
					gchar* _tmp5_;
					gchar* _tmp6_;
					_tmp5_ = dh_arg_info_help_message (arg, gettext_package);
					_tmp6_ = _tmp5_;
					g_print ("%s", _tmp6_);
					_g_free0 (_tmp6_);
					_g_free0 (str);
					continue;
				} else {
					gchar ret = '\0';
					const gchar* _tmp7_;
					_tmp7_ = str;
					ret = dh_arg_info_match_char (arg, _tmp7_);
					if (((gint) ret) != 0) {
						GValue _tmp8_ = {0};
						g_value_init (&_tmp8_, G_TYPE_CHAR);
						g_value_set_schar (&_tmp8_, ret);
						*result = _tmp8_;
						_g_free0 (str);
						return;
					}
				}
			}
			if (validator != NULL) {
				if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_INT_VALIDATOR) {
					const gchar* _tmp9_;
					_tmp9_ = str;
					if (g_regex_match_simple ("^[\\-|\\+]?[0-9]+$", _tmp9_, 0, 0)) {
						gint64 ret = 0LL;
						const gchar* _tmp10_;
						_tmp10_ = str;
						ret = int64_parse (_tmp10_, (guint) 10);
						if (dh_validator_in_field ((DhValidator*) (IS_DH_INT_VALIDATOR (validator) ? ((DhIntValidator*) validator) : NULL), &ret)) {
							GValue _tmp11_ = {0};
							g_value_init (&_tmp11_, G_TYPE_INT64);
							g_value_set_int64 (&_tmp11_, ret);
							*result = _tmp11_;
							_g_free0 (str);
							return;
						}
					}
				} else {
					if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_UINT_VALIDATOR) {
						const gchar* _tmp12_;
						_tmp12_ = str;
						if (g_regex_match_simple ("^[\\+]?[0-9]+$", _tmp12_, 0, 0)) {
							guint64 ret = 0ULL;
							const gchar* _tmp13_;
							_tmp13_ = str;
							ret = uint64_parse (_tmp13_, (guint) 10);
							if (dh_validator_in_field ((DhValidator*) (IS_DH_UINT_VALIDATOR (validator) ? ((DhUIntValidator*) validator) : NULL), &ret)) {
								GValue _tmp14_ = {0};
								g_value_init (&_tmp14_, G_TYPE_UINT64);
								g_value_set_uint64 (&_tmp14_, ret);
								*result = _tmp14_;
								_g_free0 (str);
								return;
							}
						}
					} else {
						if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_DOUBLE_VALIDATOR) {
							gchar* end_str = NULL;
							gdouble ret = 0.0;
							const gchar* _tmp15_;
							const gchar* _tmp16_ = NULL;
							gdouble _tmp17_;
							gchar* _tmp18_;
							const gchar* _tmp19_;
							_tmp15_ = str;
							_tmp17_ = g_ascii_strtod (_tmp15_, &_tmp16_);
							_g_free0 (end_str);
							_tmp18_ = g_strdup (_tmp16_);
							end_str = _tmp18_;
							ret = _tmp17_;
							_tmp19_ = end_str;
							if (g_strcmp0 (_tmp19_, "") == 0) {
								if (dh_validator_in_field ((DhValidator*) (IS_DH_DOUBLE_VALIDATOR (validator) ? ((DhDoubleValidator*) validator) : NULL), &ret)) {
									GValue _tmp20_ = {0};
									g_value_init (&_tmp20_, G_TYPE_DOUBLE);
									g_value_set_double (&_tmp20_, ret);
									*result = _tmp20_;
									_g_free0 (end_str);
									_g_free0 (str);
									return;
								}
							}
							_g_free0 (end_str);
						} else {
							if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_REGEX_VALIDATOR) {
								const gchar* _tmp21_;
								_tmp21_ = str;
								if (dh_validator_in_field ((DhValidator*) (IS_DH_REGEX_VALIDATOR (validator) ? ((DhRegexValidator*) validator) : NULL), _tmp21_)) {
									GValue _tmp22_ = {0};
									g_value_init (&_tmp22_, G_TYPE_STRING);
									g_value_take_string (&_tmp22_, str);
									*result = _tmp22_;
									return;
								}
							} else {
								if (G_TYPE_FROM_INSTANCE ((GObject*) validator) == TYPE_DH_MATCH_VALIDATOR) {
									const gchar* _tmp23_;
									_tmp23_ = str;
									if (dh_validator_in_field ((DhValidator*) (IS_DH_MATCH_VALIDATOR (validator) ? ((DhMatchValidator*) validator) : NULL), _tmp23_)) {
										GValue _tmp24_ = {0};
										g_value_init (&_tmp24_, G_TYPE_STRING);
										g_value_take_string (&_tmp24_, str);
										*result = _tmp24_;
										return;
									}
								}
							}
						}
					}
				}
			}
			g_print ("Unsuccess!\n");
		}
		_g_free0 (str);
	}
}

DhOut*
dh_out_construct (GType object_type)
{
	DhOut * self = NULL;
	self = (DhOut*) g_object_new (object_type, NULL);
	return self;
}

DhOut*
dh_out_new (void)
{
	return dh_out_construct (TYPE_DH_OUT);
}

static void
dh_out_class_init (DhOutClass * klass,
                   gpointer klass_data)
{
	dh_out_parent_class = g_type_class_peek_parent (klass);
}

static void
dh_out_instance_init (DhOut * self,
                      gpointer klass)
{
}

static GType
dh_out_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DhOutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dh_out_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DhOut), 0, (GInstanceInitFunc) dh_out_instance_init, NULL };
	GType dh_out_type_id;
	dh_out_type_id = g_type_register_static (G_TYPE_OBJECT, "DhOut", &g_define_type_info, 0);
	return dh_out_type_id;
}

GType
dh_out_get_type (void)
{
	static volatile gsize dh_out_type_id__once = 0;
	if (g_once_init_enter (&dh_out_type_id__once)) {
		GType dh_out_type_id;
		dh_out_type_id = dh_out_get_type_once ();
		g_once_init_leave (&dh_out_type_id__once, dh_out_type_id);
	}
	return dh_out_type_id__once;
}

